// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../message_deletion/types.dart';
import '../conversation.dart';
import '../conversation_bridge.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Validate the entire selection and durably apply one explicit deletion scope.
Future<DeleteMessagesResult> deleteMessages(
        {required BridgeConversationRef reference,
        required List<String> messageIds,
        required DeleteScope scope}) =>
    RustLib.instance.api.crateApiConversationDeletionDeleteMessages(
        reference: reference, messageIds: messageIds, scope: scope);
