// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../chat_names/types.dart';
import '../../frb_generated.dart';
import '../conversation.dart';
import '../conversation_bridge.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `key`

Future<ChatNameSnapshot> personalNames() =>
    RustLib.instance.api.crateApiConversationNamesPersonalNames();

Future<void> rename(
        {required BridgeConversationRef reference, required String name}) =>
    RustLib.instance.api
        .crateApiConversationNamesRename(reference: reference, name: name);

Future<void> resetName({required BridgeConversationRef reference}) =>
    RustLib.instance.api
        .crateApiConversationNamesResetName(reference: reference);
