//! Capture the identity already loaded/generated by Moss during Init.
//! Only the resulting node retains its key; no second identity or ABI is used.
use super::*;
use ed25519_dalek::SigningKey;

pub(super) static INIT_LOCK: Mutex<()> = Mutex::new(());
static CAPTURED_SIGNER: Mutex<Option<SigningKey>> = Mutex::new(None);

pub(super) fn capture_identity(bytes: &[u8]) {
    *CAPTURED_SIGNER
        .lock()
        .unwrap_or_else(|error| error.into_inner()) =
        crate::org_signing::signing_key_from_identity(bytes).ok();
}

pub(super) fn take_identity() -> Option<SigningKey> {
    CAPTURED_SIGNER
        .lock()
        .unwrap_or_else(|error| error.into_inner())
        .take()
}

impl MossNode {
    pub(crate) fn identity_signer(&self) -> Result<&SigningKey, MossFfiError> {
        self.identity_signer
            .as_ref()
            .ok_or(MossFfiError::Operation {
                name: "identity signer unavailable",
                code: -1,
            })
    }
}
