// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A portable proof names one original send, including its conversation and
/// content digest. MLS receivers additionally match this key to the actual leaf.
class MessageOrigin {
  final String conversation;
  final String id;
  final String contentHash;
  final String author;
  final String signature;
  final String? ownership;

  const MessageOrigin({
    required this.conversation,
    required this.id,
    required this.contentHash,
    required this.author,
    required this.signature,
    this.ownership,
  });

  @override
  int get hashCode =>
      conversation.hashCode ^
      id.hashCode ^
      contentHash.hashCode ^
      author.hashCode ^
      signature.hashCode ^
      ownership.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageOrigin &&
          runtimeType == other.runtimeType &&
          conversation == other.conversation &&
          id == other.id &&
          contentHash == other.contentHash &&
          author == other.author &&
          signature == other.signature &&
          ownership == other.ownership;
}
