// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'origin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class DeleteMessagesResult {
  final BigInt deletedCount;
  final BigInt localOnlyCount;
  final BigInt pendingCount;

  const DeleteMessagesResult({
    required this.deletedCount,
    required this.localOnlyCount,
    required this.pendingCount,
  });

  @override
  int get hashCode =>
      deletedCount.hashCode ^ localOnlyCount.hashCode ^ pendingCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeleteMessagesResult &&
          runtimeType == other.runtimeType &&
          deletedCount == other.deletedCount &&
          localOnlyCount == other.localOnlyCount &&
          pendingCount == other.pendingCount;
}

enum DeleteScope {
  forMe,
  forEveryone,
  ;
}

class DeletionMarker {
  final DeleteScope scope;
  final DeletionStatus status;
  final String? administrator;

  const DeletionMarker({
    required this.scope,
    required this.status,
    this.administrator,
  });

  @override
  int get hashCode => scope.hashCode ^ status.hashCode ^ administrator.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeletionMarker &&
          runtimeType == other.runtimeType &&
          scope == other.scope &&
          status == other.status &&
          administrator == other.administrator;
}

enum DeletionStatus {
  pending,
  confirmed,
  rejected,
  ;
}

class DeletionSummary {
  final BigInt pendingCount;
  final BigInt rejectedCount;

  const DeletionSummary({
    required this.pendingCount,
    required this.rejectedCount,
  });

  @override
  int get hashCode => pendingCount.hashCode ^ rejectedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeletionSummary &&
          runtimeType == other.runtimeType &&
          pendingCount == other.pendingCount &&
          rejectedCount == other.rejectedCount;
}

/// Origin and tombstone survive content erasure. Action flags are recomputed
/// by the native owner before snapshots; incoming flags never grant authority.
class MessageMetadata {
  final MessageOrigin? origin;
  final DeletionMarker? deletion;
  final String? deletionKey;
  final bool canDeleteForEveryone;
  final bool localOnly;
  final bool? isOwn;

  const MessageMetadata({
    this.origin,
    this.deletion,
    this.deletionKey,
    required this.canDeleteForEveryone,
    required this.localOnly,
    this.isOwn,
  });

  @override
  int get hashCode =>
      origin.hashCode ^
      deletion.hashCode ^
      deletionKey.hashCode ^
      canDeleteForEveryone.hashCode ^
      localOnly.hashCode ^
      isOwn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageMetadata &&
          runtimeType == other.runtimeType &&
          origin == other.origin &&
          deletion == other.deletion &&
          deletionKey == other.deletionKey &&
          canDeleteForEveryone == other.canDeleteForEveryone &&
          localOnly == other.localOnly &&
          isOwn == other.isOwn;
}
