// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class JoinChannelRequest {
  final String name;
  final String displayName;
  final int listenPort;
  final String? staticPeer;

  const JoinChannelRequest({
    required this.name,
    required this.displayName,
    required this.listenPort,
    this.staticPeer,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      displayName.hashCode ^
      listenPort.hashCode ^
      staticPeer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JoinChannelRequest &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          displayName == other.displayName &&
          listenPort == other.listenPort &&
          staticPeer == other.staticPeer;
}
