// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class MossRuntimeStatus {
  final String linkMode;
  final String libraryName;
  final List<String> requiredSymbols;
  final bool available;
  final List<String> checkedPaths;

  const MossRuntimeStatus({
    required this.linkMode,
    required this.libraryName,
    required this.requiredSymbols,
    required this.available,
    required this.checkedPaths,
  });

  @override
  int get hashCode =>
      linkMode.hashCode ^
      libraryName.hashCode ^
      requiredSymbols.hashCode ^
      available.hashCode ^
      checkedPaths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MossRuntimeStatus &&
          runtimeType == other.runtimeType &&
          linkMode == other.linkMode &&
          libraryName == other.libraryName &&
          requiredSymbols == other.requiredSymbols &&
          available == other.available &&
          checkedPaths == other.checkedPaths;
}
