// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class NetworkInterfaceInfo {
  final String name;
  final String description;
  final int index;
  final String? ipv4;
  final bool isLoopback;
  final bool isUp;

  /// True when the OS classifies this NIC as a tunnel / virtual / VPN
  /// device, regardless of its display name.
  final bool isVirtual;

  /// True when this virtual NIC looks like a privacy/corporate VPN tunnel.
  /// Overlay meshes and VM host adapters stay virtual, but do not trigger
  /// the VPN warning by themselves.
  final bool isVpn;

  /// True when this NIC is the one that actually carries public IPv4
  /// traffic right now — i.e. the interface the OS picks to reach the
  /// internet. This is deliberately a *best-route* answer (longest-prefix
  /// match plus metric), not "owns a `/0`", so split-default tunnels that
  /// install `0.0.0.0/1` + `128.0.0.0/1` instead of a default route are
  /// caught, and a stale high-metric `/0` no longer counts.
  /// Combined with `is_virtual = true` this is the single best signal
  /// that "an active VPN owns this user's traffic right now".
  final bool isDefaultRoute;

  const NetworkInterfaceInfo({
    required this.name,
    required this.description,
    required this.index,
    this.ipv4,
    required this.isLoopback,
    required this.isUp,
    required this.isVirtual,
    required this.isVpn,
    required this.isDefaultRoute,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      index.hashCode ^
      ipv4.hashCode ^
      isLoopback.hashCode ^
      isUp.hashCode ^
      isVirtual.hashCode ^
      isVpn.hashCode ^
      isDefaultRoute.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkInterfaceInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          index == other.index &&
          ipv4 == other.ipv4 &&
          isLoopback == other.isLoopback &&
          isUp == other.isUp &&
          isVirtual == other.isVirtual &&
          isVpn == other.isVpn &&
          isDefaultRoute == other.isDefaultRoute;
}
