// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum MessageDeliveryStatus {
  /// Handed to the transport, outcome not known yet. A group and a channel
  /// file a send this way for the moment the publish takes.
  pending,

  /// On disk and waiting for the counterpart to be reachable (private DM
  /// only). Survives a restart; the DM's outbox drives it out.
  queued,
  sent,

  /// The peer's runtime acknowledged receipt (private DM only). `Sent` means
  /// "handed to the transport"; only `Delivered` proves the frame arrived.
  delivered,
  failed,
  ;
}
