// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Runtime status snapshot for the persistence module. Canonical home for the
/// readiness marker the diagnostics facade reports; fields mirror the struct
/// the previous Tauri shell carried (backend id, database path, availability,
/// at-rest encryption flag, and an optional error string).
class PersistenceRuntimeStatus {
  final String backend;
  final String database;
  final bool available;
  final bool encryptedAtRest;
  final String? error;

  const PersistenceRuntimeStatus({
    required this.backend,
    required this.database,
    required this.available,
    required this.encryptedAtRest,
    this.error,
  });

  @override
  int get hashCode =>
      backend.hashCode ^
      database.hashCode ^
      available.hashCode ^
      encryptedAtRest.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersistenceRuntimeStatus &&
          runtimeType == other.runtimeType &&
          backend == other.backend &&
          database == other.database &&
          available == other.available &&
          encryptedAtRest == other.encryptedAtRest &&
          error == other.error;
}
