// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            

            

            class SecureStorageStatus  {
                final String backend;
final String service;
final bool available;

                const SecureStorageStatus({required this.backend ,required this.service ,required this.available ,});

                
                

                
        @override
        int get hashCode => backend.hashCode^service.hashCode^available.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is SecureStorageStatus &&
                runtimeType == other.runtimeType
                && backend == other.backend&& service == other.service&& available == other.available;
        
            }
            