// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../attachment_runtime.dart';
import '../conversation/attachments.dart';
import '../conversation/mesh.dart';
import '../frb_generated.dart';
import '../message_deletion/origin.dart';
import '../message_deletion/types.dart';
import '../outbound_delivery.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'transport.dart';

class AcceptInviteRequest {
  final String inviteUri;
  final String displayName;
  final int listenPort;
  final String? staticPeer;

  const AcceptInviteRequest({
    required this.inviteUri,
    required this.displayName,
    required this.listenPort,
    this.staticPeer,
  });

  @override
  int get hashCode =>
      inviteUri.hashCode ^
      displayName.hashCode ^
      listenPort.hashCode ^
      staticPeer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AcceptInviteRequest &&
          runtimeType == other.runtimeType &&
          inviteUri == other.inviteUri &&
          displayName == other.displayName &&
          listenPort == other.listenPort &&
          staticPeer == other.staticPeer;
}

class ActiveCall {
  final String callId;
  final String? supersededCallId;

  /// "caller" or "callee" — drives the nonce direction bit.
  final String direction;
  final String keyB64;
  final String noncePrefixB64;

  /// Unix millis when the call became Active; the running timer
  /// renders from this anchor.
  final BigInt startedAtMs;

  const ActiveCall({
    required this.callId,
    this.supersededCallId,
    required this.direction,
    required this.keyB64,
    required this.noncePrefixB64,
    required this.startedAtMs,
  });

  @override
  int get hashCode =>
      callId.hashCode ^
      supersededCallId.hashCode ^
      direction.hashCode ^
      keyB64.hashCode ^
      noncePrefixB64.hashCode ^
      startedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActiveCall &&
          runtimeType == other.runtimeType &&
          callId == other.callId &&
          supersededCallId == other.supersededCallId &&
          direction == other.direction &&
          keyB64 == other.keyB64 &&
          noncePrefixB64 == other.noncePrefixB64 &&
          startedAtMs == other.startedAtMs;
}

enum CallAvailability {
  busy,
  conflict,
  ;
}

class CallEvent {
  /// "completed" or "missed".
  final String kind;
  final BigInt durationMs;
  final String callId;

  const CallEvent({
    required this.kind,
    required this.durationMs,
    required this.callId,
  });

  @override
  int get hashCode => kind.hashCode ^ durationMs.hashCode ^ callId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CallEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          durationMs == other.durationMs &&
          callId == other.callId;
}

class CallStarted {
  final String sessionId;
  final String callId;
  final String keyB64;
  final String noncePrefixB64;

  const CallStarted({
    required this.sessionId,
    required this.callId,
    required this.keyB64,
    required this.noncePrefixB64,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      callId.hashCode ^
      keyB64.hashCode ^
      noncePrefixB64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CallStarted &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          callId == other.callId &&
          keyB64 == other.keyB64 &&
          noncePrefixB64 == other.noncePrefixB64;
}

class ChatMessage {
  final MessageMetadata? metadata;
  final String fromDevice;
  final String body;
  final String? messageId;
  final BigInt? sentAtMs;
  final AttachmentDescriptor? attachment;
  final CallEvent? callEvent;
  final MessageDeliveryStatus? deliveryStatus;
  final String? deliveryError;
  final bool? retryable;
  final int? retryCount;

  /// The [[Read receipt]] on the user's OWN message: `Some(true)` once the
  /// counterpart's authenticated receipt landed, absent until then (and
  /// always absent for the counterpart's messages — they have nothing to
  /// learn about their own reads). Additive and skip-when-none, so old
  /// snapshots and old history rows stay valid.
  final bool? read;

  const ChatMessage({
    this.metadata,
    required this.fromDevice,
    required this.body,
    this.messageId,
    this.sentAtMs,
    this.attachment,
    this.callEvent,
    this.deliveryStatus,
    this.deliveryError,
    this.retryable,
    this.retryCount,
    this.read,
  });

  @override
  int get hashCode =>
      metadata.hashCode ^
      fromDevice.hashCode ^
      body.hashCode ^
      messageId.hashCode ^
      sentAtMs.hashCode ^
      attachment.hashCode ^
      callEvent.hashCode ^
      deliveryStatus.hashCode ^
      deliveryError.hashCode ^
      retryable.hashCode ^
      retryCount.hashCode ^
      read.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          metadata == other.metadata &&
          fromDevice == other.fromDevice &&
          body == other.body &&
          messageId == other.messageId &&
          sentAtMs == other.sentAtMs &&
          attachment == other.attachment &&
          callEvent == other.callEvent &&
          deliveryStatus == other.deliveryStatus &&
          deliveryError == other.deliveryError &&
          retryable == other.retryable &&
          retryCount == other.retryCount &&
          read == other.read;
}

/// What the last request to reach the counterpart answered, for the
/// diagnostics card. moss keeps retrying a requested target on its own, so
/// "requested" is the good outcome; a failure means moss would not take the
/// request at all, and the runtime asks again on its next tick. The error
/// text goes to the log, where it can be read in full.
enum ConnectOutcome {
  requested,
  failed,
  ;
}

enum DmDeviceRevocationState {
  pending,
  applied,
  revoked,
  ;
}

/// Initial text history import on a linked installation. Completion is durable.
enum DmHistorySyncState {
  waitingForSource,
  importing,
  complete,
  ;
}

/// Where a DM stands, as proven by the other side. `Connected` is only
/// reached on an MLS-authenticated frame from the counterpart and only left
/// when the counterpart drops out of reach.
enum DmSessionState {
  /// Invite created or accepted; nothing from the counterpart yet.
  pending,

  /// The counterpart's handshake frame arrived, or it was connected and is
  /// out of reach now. Nothing authenticated has come back since.
  handshaking,

  /// The counterpart answered with an authenticated frame.
  connected,
  ;
}

class InviteCreated {
  final String inviteUri;
  final String sessionId;
  final String meshId;
  final String fingerprint;
  final String listenAddress;

  const InviteCreated({
    required this.inviteUri,
    required this.sessionId,
    required this.meshId,
    required this.fingerprint,
    required this.listenAddress,
  });

  @override
  int get hashCode =>
      inviteUri.hashCode ^
      sessionId.hashCode ^
      meshId.hashCode ^
      fingerprint.hashCode ^
      listenAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InviteCreated &&
          runtimeType == other.runtimeType &&
          inviteUri == other.inviteUri &&
          sessionId == other.sessionId &&
          meshId == other.meshId &&
          fingerprint == other.fingerprint &&
          listenAddress == other.listenAddress;
}

class OutgoingCall {
  final String callId;
  final String? supersededCallId;

  const OutgoingCall({
    required this.callId,
    this.supersededCallId,
  });

  @override
  int get hashCode => callId.hashCode ^ supersededCallId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutgoingCall &&
          runtimeType == other.runtimeType &&
          callId == other.callId &&
          supersededCallId == other.supersededCallId;
}

class PendingCall {
  final String callId;
  final String? supersededCallId;
  final String fromDevice;

  /// Answer requested locally; media waits for the caller's selected device.
  final bool answerPending;

  const PendingCall({
    required this.callId,
    this.supersededCallId,
    required this.fromDevice,
    required this.answerPending,
  });

  @override
  int get hashCode =>
      callId.hashCode ^
      supersededCallId.hashCode ^
      fromDevice.hashCode ^
      answerPending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingCall &&
          runtimeType == other.runtimeType &&
          callId == other.callId &&
          supersededCallId == other.supersededCallId &&
          fromDevice == other.fromDevice &&
          answerPending == other.answerPending;
}

class SessionListSnapshot {
  final List<SessionSnapshot> sessions;

  const SessionListSnapshot({
    required this.sessions,
  });

  @override
  int get hashCode => sessions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionListSnapshot &&
          runtimeType == other.runtimeType &&
          sessions == other.sessions;
}

class SessionSnapshot {
  /// Account-wide admission, including leases held by linked installations.
  final CallAvailability? callAvailability;
  final DeletionSummary? deletionSummary;
  final DmDeviceRevocationState? deviceRevocation;
  final DmHistorySyncState? historySync;
  final String sessionId;
  final String meshId;
  final String role;

  /// The local device's own display name.
  final String displayName;

  /// The remote peer's display name, learned from inbound messages/control.
  /// Empty until the first inbound frame from the peer is seen.
  final String peerDisplayName;
  final DmSessionState state;

  /// How the counterpart is reachable through moss right now.
  final PeerTransport transport;

  /// The counterpart's moss peer id, once a handshake frame carried it.
  final String? peerMossId;

  /// What the last request to reach the counterpart answered.
  final ConnectOutcome? lastConnectOutcome;
  final String? inviteUri;

  /// Durable first admission controls creator invitation actions. Offline
  /// status never makes a consumed invitation available again.
  final bool inviteAvailable;
  final String fingerprint;
  final List<ChatMessage> messages;
  final List<AttachmentView> attachments;
  final MeshInfo? mesh;
  final List<SnapshotEvent> events;
  final PendingCall? pendingCall;

  /// Wall-clock deadline of the peer's typing hint, if one stands. Absent
  /// when the peer is not typing; a poll past the deadline simply stops
  /// carrying the field.
  final BigInt? peerTypingUntilMs;

  /// Present while the local user is placing a call and waiting for the peer
  /// to answer (caller-side "ringing" state).
  final OutgoingCall? outgoingCall;
  final ActiveCall? activeCall;

  const SessionSnapshot({
    this.callAvailability,
    this.deletionSummary,
    this.deviceRevocation,
    this.historySync,
    required this.sessionId,
    required this.meshId,
    required this.role,
    required this.displayName,
    required this.peerDisplayName,
    required this.state,
    required this.transport,
    this.peerMossId,
    this.lastConnectOutcome,
    this.inviteUri,
    required this.inviteAvailable,
    required this.fingerprint,
    required this.messages,
    required this.attachments,
    this.mesh,
    required this.events,
    this.pendingCall,
    this.peerTypingUntilMs,
    this.outgoingCall,
    this.activeCall,
  });

  @override
  int get hashCode =>
      callAvailability.hashCode ^
      deletionSummary.hashCode ^
      deviceRevocation.hashCode ^
      historySync.hashCode ^
      sessionId.hashCode ^
      meshId.hashCode ^
      role.hashCode ^
      displayName.hashCode ^
      peerDisplayName.hashCode ^
      state.hashCode ^
      transport.hashCode ^
      peerMossId.hashCode ^
      lastConnectOutcome.hashCode ^
      inviteUri.hashCode ^
      inviteAvailable.hashCode ^
      fingerprint.hashCode ^
      messages.hashCode ^
      attachments.hashCode ^
      mesh.hashCode ^
      events.hashCode ^
      pendingCall.hashCode ^
      peerTypingUntilMs.hashCode ^
      outgoingCall.hashCode ^
      activeCall.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionSnapshot &&
          runtimeType == other.runtimeType &&
          callAvailability == other.callAvailability &&
          deletionSummary == other.deletionSummary &&
          deviceRevocation == other.deviceRevocation &&
          historySync == other.historySync &&
          sessionId == other.sessionId &&
          meshId == other.meshId &&
          role == other.role &&
          displayName == other.displayName &&
          peerDisplayName == other.peerDisplayName &&
          state == other.state &&
          transport == other.transport &&
          peerMossId == other.peerMossId &&
          lastConnectOutcome == other.lastConnectOutcome &&
          inviteUri == other.inviteUri &&
          inviteAvailable == other.inviteAvailable &&
          fingerprint == other.fingerprint &&
          messages == other.messages &&
          attachments == other.attachments &&
          mesh == other.mesh &&
          events == other.events &&
          pendingCall == other.pendingCall &&
          peerTypingUntilMs == other.peerTypingUntilMs &&
          outgoingCall == other.outgoingCall &&
          activeCall == other.activeCall;
}

class StartSessionRequest {
  final String displayName;
  final int listenPort;
  final String? staticPeer;

  const StartSessionRequest({
    required this.displayName,
    required this.listenPort,
    this.staticPeer,
  });

  @override
  int get hashCode =>
      displayName.hashCode ^ listenPort.hashCode ^ staticPeer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartSessionRequest &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          listenPort == other.listenPort &&
          staticPeer == other.staticPeer;
}
