// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../attachment_runtime.dart';
import '../frb_generated.dart';
import '../outbound_delivery.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AcceptInviteRequest {
  final String inviteUri;
  final String displayName;
  final int listenPort;
  final String? staticPeer;

  const AcceptInviteRequest({
    required this.inviteUri,
    required this.displayName,
    required this.listenPort,
    this.staticPeer,
  });

  @override
  int get hashCode =>
      inviteUri.hashCode ^
      displayName.hashCode ^
      listenPort.hashCode ^
      staticPeer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AcceptInviteRequest &&
          runtimeType == other.runtimeType &&
          inviteUri == other.inviteUri &&
          displayName == other.displayName &&
          listenPort == other.listenPort &&
          staticPeer == other.staticPeer;
}

class ActiveCall {
  final String callId;

  /// "caller" or "callee" — drives the nonce direction bit on the frontend.
  final String direction;
  final String keyB64;
  final String noncePrefixB64;

  /// Unix millis when the call became Active. The frontend renders the
  /// running timer from this anchor.
  final BigInt startedAtMs;

  const ActiveCall({
    required this.callId,
    required this.direction,
    required this.keyB64,
    required this.noncePrefixB64,
    required this.startedAtMs,
  });

  @override
  int get hashCode =>
      callId.hashCode ^
      direction.hashCode ^
      keyB64.hashCode ^
      noncePrefixB64.hashCode ^
      startedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActiveCall &&
          runtimeType == other.runtimeType &&
          callId == other.callId &&
          direction == other.direction &&
          keyB64 == other.keyB64 &&
          noncePrefixB64 == other.noncePrefixB64 &&
          startedAtMs == other.startedAtMs;
}

/// Immutable attachment metadata stamped onto the message log. Mutable
/// transfer state is reported separately through AttachmentView.
class AttachmentDescriptor {
  final String attachmentId;
  final String contentHash;
  final String fileName;
  final String mime;
  final BigInt totalSize;
  final String? thumbnailB64;
  final VoiceMeta? voice;

  const AttachmentDescriptor({
    required this.attachmentId,
    required this.contentHash,
    required this.fileName,
    required this.mime,
    required this.totalSize,
    this.thumbnailB64,
    this.voice,
  });

  @override
  int get hashCode =>
      attachmentId.hashCode ^
      contentHash.hashCode ^
      fileName.hashCode ^
      mime.hashCode ^
      totalSize.hashCode ^
      thumbnailB64.hashCode ^
      voice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttachmentDescriptor &&
          runtimeType == other.runtimeType &&
          attachmentId == other.attachmentId &&
          contentHash == other.contentHash &&
          fileName == other.fileName &&
          mime == other.mime &&
          totalSize == other.totalSize &&
          thumbnailB64 == other.thumbnailB64 &&
          voice == other.voice;
}

class AttachmentSendResult {
  final String sessionId;
  final String attachmentId;
  final String contentHash;

  const AttachmentSendResult({
    required this.sessionId,
    required this.attachmentId,
    required this.contentHash,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^ attachmentId.hashCode ^ contentHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttachmentSendResult &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          attachmentId == other.attachmentId &&
          contentHash == other.contentHash;
}

enum AttachmentState {
  /// Bytes are on disk locally (sender's own file, or a finished download).
  available,

  /// Manifest known, download not started yet.
  offered,

  /// Chunks are in flight.
  downloading,

  /// Transfer or verification failed; a retry is possible.
  failed,

  /// Either side cancelled the transfer.
  cancelled,
  ;
}

/// Live transfer state for one attachment, recomputed on every snapshot.
class AttachmentView {
  final String attachmentId;
  final String direction;
  final AttachmentState state;
  final BigInt completedChunks;
  final BigInt chunkCount;
  final String? localPath;

  const AttachmentView({
    required this.attachmentId,
    required this.direction,
    required this.state,
    required this.completedChunks,
    required this.chunkCount,
    this.localPath,
  });

  @override
  int get hashCode =>
      attachmentId.hashCode ^
      direction.hashCode ^
      state.hashCode ^
      completedChunks.hashCode ^
      chunkCount.hashCode ^
      localPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttachmentView &&
          runtimeType == other.runtimeType &&
          attachmentId == other.attachmentId &&
          direction == other.direction &&
          state == other.state &&
          completedChunks == other.completedChunks &&
          chunkCount == other.chunkCount &&
          localPath == other.localPath;
}

class CallEvent {
  /// "completed" or "missed".
  final String kind;
  final BigInt durationMs;
  final String callId;

  const CallEvent({
    required this.kind,
    required this.durationMs,
    required this.callId,
  });

  @override
  int get hashCode => kind.hashCode ^ durationMs.hashCode ^ callId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CallEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          durationMs == other.durationMs &&
          callId == other.callId;
}

class CallStarted {
  final String sessionId;
  final String callId;
  final String keyB64;
  final String noncePrefixB64;

  const CallStarted({
    required this.sessionId,
    required this.callId,
    required this.keyB64,
    required this.noncePrefixB64,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      callId.hashCode ^
      keyB64.hashCode ^
      noncePrefixB64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CallStarted &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          callId == other.callId &&
          keyB64 == other.keyB64 &&
          noncePrefixB64 == other.noncePrefixB64;
}

class ChatMessage {
  final String fromDevice;
  final String body;
  final String? messageId;
  final BigInt? sentAtMs;
  final AttachmentDescriptor? attachment;
  final CallEvent? callEvent;
  final MessageDeliveryStatus? deliveryStatus;
  final String? deliveryError;
  final bool? retryable;
  final int? retryCount;

  const ChatMessage({
    required this.fromDevice,
    required this.body,
    this.messageId,
    this.sentAtMs,
    this.attachment,
    this.callEvent,
    this.deliveryStatus,
    this.deliveryError,
    this.retryable,
    this.retryCount,
  });

  @override
  int get hashCode =>
      fromDevice.hashCode ^
      body.hashCode ^
      messageId.hashCode ^
      sentAtMs.hashCode ^
      attachment.hashCode ^
      callEvent.hashCode ^
      deliveryStatus.hashCode ^
      deliveryError.hashCode ^
      retryable.hashCode ^
      retryCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          fromDevice == other.fromDevice &&
          body == other.body &&
          messageId == other.messageId &&
          sentAtMs == other.sentAtMs &&
          attachment == other.attachment &&
          callEvent == other.callEvent &&
          deliveryStatus == other.deliveryStatus &&
          deliveryError == other.deliveryError &&
          retryable == other.retryable &&
          retryCount == other.retryCount;
}

class CloseSessionResult {
  final String sessionId;
  final bool closed;

  const CloseSessionResult({
    required this.sessionId,
    required this.closed,
  });

  @override
  int get hashCode => sessionId.hashCode ^ closed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloseSessionResult &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          closed == other.closed;
}

/// A request to start a private DM, surfaced inside a channel or group. The
/// initiator publishes it; the targeted member accepts the carried invite.
class DmOffer {
  final String offerId;
  final String fromDevice;
  final String fromFingerprint;
  final String targetFingerprint;
  final String inviteUri;

  const DmOffer({
    required this.offerId,
    required this.fromDevice,
    required this.fromFingerprint,
    required this.targetFingerprint,
    required this.inviteUri,
  });

  @override
  int get hashCode =>
      offerId.hashCode ^
      fromDevice.hashCode ^
      fromFingerprint.hashCode ^
      targetFingerprint.hashCode ^
      inviteUri.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DmOffer &&
          runtimeType == other.runtimeType &&
          offerId == other.offerId &&
          fromDevice == other.fromDevice &&
          fromFingerprint == other.fromFingerprint &&
          targetFingerprint == other.targetFingerprint &&
          inviteUri == other.inviteUri;
}

class InviteCreated {
  final String inviteUri;
  final String sessionId;
  final String meshId;
  final String fingerprint;
  final String listenAddress;

  const InviteCreated({
    required this.inviteUri,
    required this.sessionId,
    required this.meshId,
    required this.fingerprint,
    required this.listenAddress,
  });

  @override
  int get hashCode =>
      inviteUri.hashCode ^
      sessionId.hashCode ^
      meshId.hashCode ^
      fingerprint.hashCode ^
      listenAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InviteCreated &&
          runtimeType == other.runtimeType &&
          inviteUri == other.inviteUri &&
          sessionId == other.sessionId &&
          meshId == other.meshId &&
          fingerprint == other.fingerprint &&
          listenAddress == other.listenAddress;
}

class MeshInfo {
  final String meshId;
  final int listenPort;
  final String advertisedAddr;
  final int peerCount;
  final int directPeerCount;
  final int relayedPeerCount;
  final int relayCapablePeerCount;
  final int relaySessionCount;
  final int relayRouteCount;
  final int knownPeerCount;
  final List<String> channels;
  final String natType;
  final bool supernodeReady;
  final String publicKey;

  /// Per-peer identity of every currently connected peer. On the shared
  /// substrate a node connects network-wide, so `direct_peer_count` counts
  /// unrelated world peers; presence for one counterpart must match this list
  /// by `id` (the peer's moss public-key hex) instead of trusting a count.
  final List<PeerDetail> peerDetails;

  const MeshInfo({
    required this.meshId,
    required this.listenPort,
    required this.advertisedAddr,
    required this.peerCount,
    required this.directPeerCount,
    required this.relayedPeerCount,
    required this.relayCapablePeerCount,
    required this.relaySessionCount,
    required this.relayRouteCount,
    required this.knownPeerCount,
    required this.channels,
    required this.natType,
    required this.supernodeReady,
    required this.publicKey,
    required this.peerDetails,
  });

  @override
  int get hashCode =>
      meshId.hashCode ^
      listenPort.hashCode ^
      advertisedAddr.hashCode ^
      peerCount.hashCode ^
      directPeerCount.hashCode ^
      relayedPeerCount.hashCode ^
      relayCapablePeerCount.hashCode ^
      relaySessionCount.hashCode ^
      relayRouteCount.hashCode ^
      knownPeerCount.hashCode ^
      channels.hashCode ^
      natType.hashCode ^
      supernodeReady.hashCode ^
      publicKey.hashCode ^
      peerDetails.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeshInfo &&
          runtimeType == other.runtimeType &&
          meshId == other.meshId &&
          listenPort == other.listenPort &&
          advertisedAddr == other.advertisedAddr &&
          peerCount == other.peerCount &&
          directPeerCount == other.directPeerCount &&
          relayedPeerCount == other.relayedPeerCount &&
          relayCapablePeerCount == other.relayCapablePeerCount &&
          relaySessionCount == other.relaySessionCount &&
          relayRouteCount == other.relayRouteCount &&
          knownPeerCount == other.knownPeerCount &&
          channels == other.channels &&
          natType == other.natType &&
          supernodeReady == other.supernodeReady &&
          publicKey == other.publicKey &&
          peerDetails == other.peerDetails;
}

class OutgoingCall {
  final String callId;

  const OutgoingCall({
    required this.callId,
  });

  @override
  int get hashCode => callId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutgoingCall &&
          runtimeType == other.runtimeType &&
          callId == other.callId;
}

class PeerDetail {
  final String id;
  final String addr;
  final bool relayed;

  const PeerDetail({
    required this.id,
    required this.addr,
    required this.relayed,
  });

  @override
  int get hashCode => id.hashCode ^ addr.hashCode ^ relayed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerDetail &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          addr == other.addr &&
          relayed == other.relayed;
}

class PendingCall {
  final String callId;
  final String fromDevice;

  const PendingCall({
    required this.callId,
    required this.fromDevice,
  });

  @override
  int get hashCode => callId.hashCode ^ fromDevice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingCall &&
          runtimeType == other.runtimeType &&
          callId == other.callId &&
          fromDevice == other.fromDevice;
}

class SendMessageResult {
  final String sessionId;
  final String state;
  final BigInt ciphertextBytes;
  final String messageId;
  final BigInt sentAtMs;
  final MessageDeliveryStatus deliveryStatus;
  final String? deliveryError;

  const SendMessageResult({
    required this.sessionId,
    required this.state,
    required this.ciphertextBytes,
    required this.messageId,
    required this.sentAtMs,
    required this.deliveryStatus,
    this.deliveryError,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      state.hashCode ^
      ciphertextBytes.hashCode ^
      messageId.hashCode ^
      sentAtMs.hashCode ^
      deliveryStatus.hashCode ^
      deliveryError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendMessageResult &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          state == other.state &&
          ciphertextBytes == other.ciphertextBytes &&
          messageId == other.messageId &&
          sentAtMs == other.sentAtMs &&
          deliveryStatus == other.deliveryStatus &&
          deliveryError == other.deliveryError;
}

class SessionListSnapshot {
  final List<SessionSnapshot> sessions;

  const SessionListSnapshot({
    required this.sessions,
  });

  @override
  int get hashCode => sessions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionListSnapshot &&
          runtimeType == other.runtimeType &&
          sessions == other.sessions;
}

class SessionSnapshot {
  final String sessionId;
  final String meshId;
  final String role;

  /// The local device's own display name.
  final String displayName;

  /// The remote peer's display name, learned from inbound messages/control.
  /// Empty until the first inbound frame from the peer is seen.
  final String peerDisplayName;
  final String state;

  /// Which transport this DM currently uses: "direct", "relayed", or
  /// "connecting". Relayed traffic is still E2E — the supernode sees only
  /// ciphertext.
  final String path;

  /// Whether the shared relay node currently sees at least one
  /// relay-capable peer (a promoted SuperNode). Only present while `path`
  /// is "relayed"; `false` means the relay is still warming up — queued
  /// frames wait for convergence instead of failing.
  final bool? relayReady;
  final String? inviteUri;
  final String fingerprint;
  final List<ChatMessage> messages;
  final List<AttachmentView> attachments;
  final MeshInfo? mesh;
  final List<SnapshotEvent> events;
  final PendingCall? pendingCall;

  /// Present while the local user is placing a call and waiting for the peer
  /// to answer (caller-side "ringing" state).
  final OutgoingCall? outgoingCall;
  final ActiveCall? activeCall;

  const SessionSnapshot({
    required this.sessionId,
    required this.meshId,
    required this.role,
    required this.displayName,
    required this.peerDisplayName,
    required this.state,
    required this.path,
    this.relayReady,
    this.inviteUri,
    required this.fingerprint,
    required this.messages,
    required this.attachments,
    this.mesh,
    required this.events,
    this.pendingCall,
    this.outgoingCall,
    this.activeCall,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      meshId.hashCode ^
      role.hashCode ^
      displayName.hashCode ^
      peerDisplayName.hashCode ^
      state.hashCode ^
      path.hashCode ^
      relayReady.hashCode ^
      inviteUri.hashCode ^
      fingerprint.hashCode ^
      messages.hashCode ^
      attachments.hashCode ^
      mesh.hashCode ^
      events.hashCode ^
      pendingCall.hashCode ^
      outgoingCall.hashCode ^
      activeCall.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionSnapshot &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          meshId == other.meshId &&
          role == other.role &&
          displayName == other.displayName &&
          peerDisplayName == other.peerDisplayName &&
          state == other.state &&
          path == other.path &&
          relayReady == other.relayReady &&
          inviteUri == other.inviteUri &&
          fingerprint == other.fingerprint &&
          messages == other.messages &&
          attachments == other.attachments &&
          mesh == other.mesh &&
          events == other.events &&
          pendingCall == other.pendingCall &&
          outgoingCall == other.outgoingCall &&
          activeCall == other.activeCall;
}

class SnapshotEvent {
  final int eventType;
  final String eventName;
  final String detailJson;
  final BigInt epochMillis;

  const SnapshotEvent({
    required this.eventType,
    required this.eventName,
    required this.detailJson,
    required this.epochMillis,
  });

  @override
  int get hashCode =>
      eventType.hashCode ^
      eventName.hashCode ^
      detailJson.hashCode ^
      epochMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SnapshotEvent &&
          runtimeType == other.runtimeType &&
          eventType == other.eventType &&
          eventName == other.eventName &&
          detailJson == other.detailJson &&
          epochMillis == other.epochMillis;
}

class StartSessionRequest {
  final String displayName;
  final int listenPort;
  final String? staticPeer;

  const StartSessionRequest({
    required this.displayName,
    required this.listenPort,
    this.staticPeer,
  });

  @override
  int get hashCode =>
      displayName.hashCode ^ listenPort.hashCode ^ staticPeer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartSessionRequest &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          listenPort == other.listenPort &&
          staticPeer == other.staticPeer;
}
