// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../attachment_runtime.dart';
import '../conversation/attachments.dart';
import '../conversation/mesh.dart';
import '../frb_generated.dart';
import '../outbound_delivery.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'transport.dart';

class AcceptInviteRequest {
  final String inviteUri;
  final String displayName;
  final int listenPort;
  final String? staticPeer;

  const AcceptInviteRequest({
    required this.inviteUri,
    required this.displayName,
    required this.listenPort,
    this.staticPeer,
  });

  @override
  int get hashCode =>
      inviteUri.hashCode ^
      displayName.hashCode ^
      listenPort.hashCode ^
      staticPeer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AcceptInviteRequest &&
          runtimeType == other.runtimeType &&
          inviteUri == other.inviteUri &&
          displayName == other.displayName &&
          listenPort == other.listenPort &&
          staticPeer == other.staticPeer;
}

class ActiveCall {
  final String callId;

  /// "caller" or "callee" — drives the nonce direction bit on the frontend.
  final String direction;
  final String keyB64;
  final String noncePrefixB64;

  /// Unix millis when the call became Active. The frontend renders the
  /// running timer from this anchor.
  final BigInt startedAtMs;

  const ActiveCall({
    required this.callId,
    required this.direction,
    required this.keyB64,
    required this.noncePrefixB64,
    required this.startedAtMs,
  });

  @override
  int get hashCode =>
      callId.hashCode ^
      direction.hashCode ^
      keyB64.hashCode ^
      noncePrefixB64.hashCode ^
      startedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActiveCall &&
          runtimeType == other.runtimeType &&
          callId == other.callId &&
          direction == other.direction &&
          keyB64 == other.keyB64 &&
          noncePrefixB64 == other.noncePrefixB64 &&
          startedAtMs == other.startedAtMs;
}

class CallEvent {
  /// "completed" or "missed".
  final String kind;
  final BigInt durationMs;
  final String callId;

  const CallEvent({
    required this.kind,
    required this.durationMs,
    required this.callId,
  });

  @override
  int get hashCode => kind.hashCode ^ durationMs.hashCode ^ callId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CallEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          durationMs == other.durationMs &&
          callId == other.callId;
}

class CallStarted {
  final String sessionId;
  final String callId;
  final String keyB64;
  final String noncePrefixB64;

  const CallStarted({
    required this.sessionId,
    required this.callId,
    required this.keyB64,
    required this.noncePrefixB64,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      callId.hashCode ^
      keyB64.hashCode ^
      noncePrefixB64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CallStarted &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          callId == other.callId &&
          keyB64 == other.keyB64 &&
          noncePrefixB64 == other.noncePrefixB64;
}

class ChatMessage {
  final String fromDevice;
  final String body;
  final String? messageId;
  final BigInt? sentAtMs;
  final AttachmentDescriptor? attachment;
  final CallEvent? callEvent;
  final MessageDeliveryStatus? deliveryStatus;
  final String? deliveryError;
  final bool? retryable;
  final int? retryCount;

  const ChatMessage({
    required this.fromDevice,
    required this.body,
    this.messageId,
    this.sentAtMs,
    this.attachment,
    this.callEvent,
    this.deliveryStatus,
    this.deliveryError,
    this.retryable,
    this.retryCount,
  });

  @override
  int get hashCode =>
      fromDevice.hashCode ^
      body.hashCode ^
      messageId.hashCode ^
      sentAtMs.hashCode ^
      attachment.hashCode ^
      callEvent.hashCode ^
      deliveryStatus.hashCode ^
      deliveryError.hashCode ^
      retryable.hashCode ^
      retryCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          fromDevice == other.fromDevice &&
          body == other.body &&
          messageId == other.messageId &&
          sentAtMs == other.sentAtMs &&
          attachment == other.attachment &&
          callEvent == other.callEvent &&
          deliveryStatus == other.deliveryStatus &&
          deliveryError == other.deliveryError &&
          retryable == other.retryable &&
          retryCount == other.retryCount;
}

/// What the last request to reach the counterpart answered, for the
/// diagnostics card. moss keeps retrying a requested target on its own, so
/// "requested" is the good outcome; a failure means moss would not take the
/// request at all, and the runtime asks again on its next tick. The error
/// text goes to the log, where it can be read in full.
enum ConnectOutcome {
  requested,
  failed,
  ;
}

/// Where a DM stands, as proven by the other side. `Connected` is only
/// reached on an MLS-authenticated frame from the counterpart and only left
/// when the counterpart drops out of reach.
enum DmSessionState {
  /// Invite created or accepted; nothing from the counterpart yet.
  pending,

  /// The counterpart's handshake frame arrived, or it was connected and is
  /// out of reach now. Nothing authenticated has come back since.
  handshaking,

  /// The counterpart answered with an authenticated frame.
  connected,
  ;
}

class InviteCreated {
  final String inviteUri;
  final String sessionId;
  final String meshId;
  final String fingerprint;
  final String listenAddress;

  const InviteCreated({
    required this.inviteUri,
    required this.sessionId,
    required this.meshId,
    required this.fingerprint,
    required this.listenAddress,
  });

  @override
  int get hashCode =>
      inviteUri.hashCode ^
      sessionId.hashCode ^
      meshId.hashCode ^
      fingerprint.hashCode ^
      listenAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InviteCreated &&
          runtimeType == other.runtimeType &&
          inviteUri == other.inviteUri &&
          sessionId == other.sessionId &&
          meshId == other.meshId &&
          fingerprint == other.fingerprint &&
          listenAddress == other.listenAddress;
}

class OutgoingCall {
  final String callId;

  const OutgoingCall({
    required this.callId,
  });

  @override
  int get hashCode => callId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutgoingCall &&
          runtimeType == other.runtimeType &&
          callId == other.callId;
}

class PendingCall {
  final String callId;
  final String fromDevice;

  const PendingCall({
    required this.callId,
    required this.fromDevice,
  });

  @override
  int get hashCode => callId.hashCode ^ fromDevice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingCall &&
          runtimeType == other.runtimeType &&
          callId == other.callId &&
          fromDevice == other.fromDevice;
}

class SessionListSnapshot {
  final List<SessionSnapshot> sessions;

  const SessionListSnapshot({
    required this.sessions,
  });

  @override
  int get hashCode => sessions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionListSnapshot &&
          runtimeType == other.runtimeType &&
          sessions == other.sessions;
}

class SessionSnapshot {
  final String sessionId;
  final String meshId;
  final String role;

  /// The local device's own display name.
  final String displayName;

  /// The remote peer's display name, learned from inbound messages/control.
  /// Empty until the first inbound frame from the peer is seen.
  final String peerDisplayName;
  final DmSessionState state;

  /// How the counterpart is reachable through moss right now.
  final PeerTransport transport;

  /// The counterpart's moss peer id, once a handshake frame carried it.
  final String? peerMossId;

  /// What the last request to reach the counterpart answered.
  final ConnectOutcome? lastConnectOutcome;
  final String? inviteUri;
  final String fingerprint;
  final List<ChatMessage> messages;
  final List<AttachmentView> attachments;
  final MeshInfo? mesh;
  final List<SnapshotEvent> events;
  final PendingCall? pendingCall;

  /// Present while the local user is placing a call and waiting for the peer
  /// to answer (caller-side "ringing" state).
  final OutgoingCall? outgoingCall;
  final ActiveCall? activeCall;

  const SessionSnapshot({
    required this.sessionId,
    required this.meshId,
    required this.role,
    required this.displayName,
    required this.peerDisplayName,
    required this.state,
    required this.transport,
    this.peerMossId,
    this.lastConnectOutcome,
    this.inviteUri,
    required this.fingerprint,
    required this.messages,
    required this.attachments,
    this.mesh,
    required this.events,
    this.pendingCall,
    this.outgoingCall,
    this.activeCall,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      meshId.hashCode ^
      role.hashCode ^
      displayName.hashCode ^
      peerDisplayName.hashCode ^
      state.hashCode ^
      transport.hashCode ^
      peerMossId.hashCode ^
      lastConnectOutcome.hashCode ^
      inviteUri.hashCode ^
      fingerprint.hashCode ^
      messages.hashCode ^
      attachments.hashCode ^
      mesh.hashCode ^
      events.hashCode ^
      pendingCall.hashCode ^
      outgoingCall.hashCode ^
      activeCall.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionSnapshot &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          meshId == other.meshId &&
          role == other.role &&
          displayName == other.displayName &&
          peerDisplayName == other.peerDisplayName &&
          state == other.state &&
          transport == other.transport &&
          peerMossId == other.peerMossId &&
          lastConnectOutcome == other.lastConnectOutcome &&
          inviteUri == other.inviteUri &&
          fingerprint == other.fingerprint &&
          messages == other.messages &&
          attachments == other.attachments &&
          mesh == other.mesh &&
          events == other.events &&
          pendingCall == other.pendingCall &&
          outgoingCall == other.outgoingCall &&
          activeCall == other.activeCall;
}

class StartSessionRequest {
  final String displayName;
  final int listenPort;
  final String? staticPeer;

  const StartSessionRequest({
    required this.displayName,
    required this.listenPort,
    this.staticPeer,
  });

  @override
  int get hashCode =>
      displayName.hashCode ^ listenPort.hashCode ^ staticPeer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartSessionRequest &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          listenPort == other.listenPort &&
          staticPeer == other.staticPeer;
}
