// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// How the counterpart is reachable through the transport right now.
enum PeerTransport {
  direct,

  /// Through moss's own network relay. Still end to end: the relay sees only
  /// ciphertext.
  relayed,

  /// Not reachable, or the peer is not known yet.
  none,
  ;
}
