// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../attachment_runtime.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Immutable attachment metadata stamped onto the message log. Mutable
/// transfer state is reported separately through [`AttachmentView`].
class AttachmentDescriptor {
  final String attachmentId;
  final String contentHash;
  final String fileName;
  final String mime;
  final BigInt totalSize;
  final String? thumbnailB64;
  final VoiceMeta? voice;

  const AttachmentDescriptor({
    required this.attachmentId,
    required this.contentHash,
    required this.fileName,
    required this.mime,
    required this.totalSize,
    this.thumbnailB64,
    this.voice,
  });

  @override
  int get hashCode =>
      attachmentId.hashCode ^
      contentHash.hashCode ^
      fileName.hashCode ^
      mime.hashCode ^
      totalSize.hashCode ^
      thumbnailB64.hashCode ^
      voice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttachmentDescriptor &&
          runtimeType == other.runtimeType &&
          attachmentId == other.attachmentId &&
          contentHash == other.contentHash &&
          fileName == other.fileName &&
          mime == other.mime &&
          totalSize == other.totalSize &&
          thumbnailB64 == other.thumbnailB64 &&
          voice == other.voice;
}

/// What a kind answers when the user sends a file.
class AttachmentSendResult {
  final String sessionId;
  final String attachmentId;
  final String contentHash;

  const AttachmentSendResult({
    required this.sessionId,
    required this.attachmentId,
    required this.contentHash,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^ attachmentId.hashCode ^ contentHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttachmentSendResult &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          attachmentId == other.attachmentId &&
          contentHash == other.contentHash;
}

enum AttachmentState {
  /// Bytes are on disk locally (sender's own file, or a finished download).
  available,

  /// Manifest known, download not started yet.
  offered,

  /// Chunks are in flight.
  downloading,

  /// Transfer or verification failed; a retry is possible.
  failed,

  /// Either side cancelled the transfer.
  cancelled,
  ;
}

/// Live transfer state for one attachment, recomputed on every snapshot.
class AttachmentView {
  final String attachmentId;
  final String direction;
  final AttachmentState state;
  final BigInt completedChunks;
  final BigInt chunkCount;
  final String? localPath;

  const AttachmentView({
    required this.attachmentId,
    required this.direction,
    required this.state,
    required this.completedChunks,
    required this.chunkCount,
    this.localPath,
  });

  @override
  int get hashCode =>
      attachmentId.hashCode ^
      direction.hashCode ^
      state.hashCode ^
      completedChunks.hashCode ^
      chunkCount.hashCode ^
      localPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttachmentView &&
          runtimeType == other.runtimeType &&
          attachmentId == other.attachmentId &&
          direction == other.direction &&
          state == other.state &&
          completedChunks == other.completedChunks &&
          chunkCount == other.chunkCount &&
          localPath == other.localPath;
}
