// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A request to start a private DM, surfaced inside a channel or group. The
/// initiator publishes it; the targeted member accepts the carried invite.
class DmOffer {
  final String offerId;
  final String fromDevice;
  final String fromFingerprint;
  final String targetFingerprint;
  final String inviteUri;

  const DmOffer({
    required this.offerId,
    required this.fromDevice,
    required this.fromFingerprint,
    required this.targetFingerprint,
    required this.inviteUri,
  });

  @override
  int get hashCode =>
      offerId.hashCode ^
      fromDevice.hashCode ^
      fromFingerprint.hashCode ^
      targetFingerprint.hashCode ^
      inviteUri.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DmOffer &&
          runtimeType == other.runtimeType &&
          offerId == other.offerId &&
          fromDevice == other.fromDevice &&
          fromFingerprint == other.fromFingerprint &&
          targetFingerprint == other.targetFingerprint &&
          inviteUri == other.inviteUri;
}
