// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// How the mesh looks to this node right now.
class MeshInfo {
  final String meshId;
  final int listenPort;
  final String advertisedAddr;
  final int peerCount;
  final int directPeerCount;
  final int relayedPeerCount;
  final int relayCapablePeerCount;
  final int relaySessionCount;
  final int relayRouteCount;
  final int knownPeerCount;
  final List<String> channels;
  final String natType;
  final bool supernodeReady;
  final String publicKey;

  /// Per-peer identity of every currently connected peer. On the shared
  /// substrate a node connects network-wide, so `direct_peer_count` counts
  /// unrelated world peers; presence for one counterpart must match this list
  /// by `id` (the peer's moss public-key hex) instead of trusting a count.
  final List<PeerDetail> peerDetails;

  const MeshInfo({
    required this.meshId,
    required this.listenPort,
    required this.advertisedAddr,
    required this.peerCount,
    required this.directPeerCount,
    required this.relayedPeerCount,
    required this.relayCapablePeerCount,
    required this.relaySessionCount,
    required this.relayRouteCount,
    required this.knownPeerCount,
    required this.channels,
    required this.natType,
    required this.supernodeReady,
    required this.publicKey,
    required this.peerDetails,
  });

  @override
  int get hashCode =>
      meshId.hashCode ^
      listenPort.hashCode ^
      advertisedAddr.hashCode ^
      peerCount.hashCode ^
      directPeerCount.hashCode ^
      relayedPeerCount.hashCode ^
      relayCapablePeerCount.hashCode ^
      relaySessionCount.hashCode ^
      relayRouteCount.hashCode ^
      knownPeerCount.hashCode ^
      channels.hashCode ^
      natType.hashCode ^
      supernodeReady.hashCode ^
      publicKey.hashCode ^
      peerDetails.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeshInfo &&
          runtimeType == other.runtimeType &&
          meshId == other.meshId &&
          listenPort == other.listenPort &&
          advertisedAddr == other.advertisedAddr &&
          peerCount == other.peerCount &&
          directPeerCount == other.directPeerCount &&
          relayedPeerCount == other.relayedPeerCount &&
          relayCapablePeerCount == other.relayCapablePeerCount &&
          relaySessionCount == other.relaySessionCount &&
          relayRouteCount == other.relayRouteCount &&
          knownPeerCount == other.knownPeerCount &&
          channels == other.channels &&
          natType == other.natType &&
          supernodeReady == other.supernodeReady &&
          publicKey == other.publicKey &&
          peerDetails == other.peerDetails;
}

/// One connected peer, as the node names it.
class PeerDetail {
  final String id;
  final String addr;
  final bool relayed;

  const PeerDetail({
    required this.id,
    required this.addr,
    required this.relayed,
  });

  @override
  int get hashCode => id.hashCode ^ addr.hashCode ^ relayed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerDetail &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          addr == other.addr &&
          relayed == other.relayed;
}

/// One thing the node reported, as the diagnostics panel shows it.
class SnapshotEvent {
  final int eventType;
  final String eventName;
  final String detailJson;
  final BigInt epochMillis;

  const SnapshotEvent({
    required this.eventType,
    required this.eventName,
    required this.detailJson,
    required this.epochMillis,
  });

  @override
  int get hashCode =>
      eventType.hashCode ^
      eventName.hashCode ^
      detailJson.hashCode ^
      epochMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SnapshotEvent &&
          runtimeType == other.runtimeType &&
          eventType == other.eventType &&
          eventName == other.eventName &&
          detailJson == other.detailJson &&
          epochMillis == other.epochMillis;
}
