// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class DeviceDescriptor {
  final String deviceId;
  final String signingPublicKey;
  final String mossPeerId;
  final String name;

  const DeviceDescriptor({
    required this.deviceId,
    required this.signingPublicKey,
    required this.mossPeerId,
    required this.name,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      signingPublicKey.hashCode ^
      mossPeerId.hashCode ^
      name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceDescriptor &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          signingPublicKey == other.signingPublicKey &&
          mossPeerId == other.mossPeerId &&
          name == other.name;
}

class DeviceLinkError implements FrbException {
  final DeviceLinkErrorKind kind;
  final String message;

  const DeviceLinkError({
    required this.kind,
    required this.message,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceLinkError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

enum DeviceLinkErrorKind {
  invalidQr,
  expired,
  busy,
  ineligible,
  codeMismatch,
  rejected,
  connectionLost,
  invalidRoster,
  storage,
  unavailable,
  ;
}

enum DeviceLinkPhase {
  idle,
  showingQr,
  connecting,
  awaitingApproval,
  awaitingConfirmation,
  delivering,
  linked,
  failed,
  ;
}

class DeviceLinkSnapshot {
  final String userId;
  final String ownDeviceId;
  final List<DeviceDescriptor> devices;
  final bool canJoin;
  final DeviceLinkPhase phase;
  final String? qrUri;
  final BigInt? expiresAt;
  final String? confirmationCode;
  final DeviceDescriptor? pendingDevice;
  final DeviceLinkErrorKind? error;

  const DeviceLinkSnapshot({
    required this.userId,
    required this.ownDeviceId,
    required this.devices,
    required this.canJoin,
    required this.phase,
    this.qrUri,
    this.expiresAt,
    this.confirmationCode,
    this.pendingDevice,
    this.error,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      ownDeviceId.hashCode ^
      devices.hashCode ^
      canJoin.hashCode ^
      phase.hashCode ^
      qrUri.hashCode ^
      expiresAt.hashCode ^
      confirmationCode.hashCode ^
      pendingDevice.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceLinkSnapshot &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          ownDeviceId == other.ownDeviceId &&
          devices == other.devices &&
          canJoin == other.canJoin &&
          phase == other.phase &&
          qrUri == other.qrUri &&
          expiresAt == other.expiresAt &&
          confirmationCode == other.confirmationCode &&
          pendingDevice == other.pendingDevice &&
          error == other.error;
}
