// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../attachment_runtime.dart';
import '../conversation/attachments.dart';
import '../conversation/dm_offers.dart';
import '../conversation/mesh.dart';
import '../frb_generated.dart';
import '../message_deletion/origin.dart';
import '../message_deletion/types.dart';
import '../outbound_delivery.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ChannelListSnapshot {
  final List<ChannelSnapshot> channels;

  const ChannelListSnapshot({
    required this.channels,
  });

  @override
  int get hashCode => channels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelListSnapshot &&
          runtimeType == other.runtimeType &&
          channels == other.channels;
}

class ChannelMessage {
  final MessageMetadata? metadata;
  final String fromDevice;
  final String fromFingerprint;
  final String body;
  final String? messageId;
  final BigInt? sentAtMs;
  final AttachmentDescriptor? attachment;
  final MessageDeliveryStatus? deliveryStatus;
  final String? deliveryError;
  final bool? retryable;
  final int? retryCount;

  const ChannelMessage({
    this.metadata,
    required this.fromDevice,
    required this.fromFingerprint,
    required this.body,
    this.messageId,
    this.sentAtMs,
    this.attachment,
    this.deliveryStatus,
    this.deliveryError,
    this.retryable,
    this.retryCount,
  });

  @override
  int get hashCode =>
      metadata.hashCode ^
      fromDevice.hashCode ^
      fromFingerprint.hashCode ^
      body.hashCode ^
      messageId.hashCode ^
      sentAtMs.hashCode ^
      attachment.hashCode ^
      deliveryStatus.hashCode ^
      deliveryError.hashCode ^
      retryable.hashCode ^
      retryCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelMessage &&
          runtimeType == other.runtimeType &&
          metadata == other.metadata &&
          fromDevice == other.fromDevice &&
          fromFingerprint == other.fromFingerprint &&
          body == other.body &&
          messageId == other.messageId &&
          sentAtMs == other.sentAtMs &&
          attachment == other.attachment &&
          deliveryStatus == other.deliveryStatus &&
          deliveryError == other.deliveryError &&
          retryable == other.retryable &&
          retryCount == other.retryCount;
}

class ChannelSnapshot {
  final DeletionSummary? deletionSummary;
  final String name;
  final String topic;
  final String meshId;
  final String displayName;
  final String deviceFingerprint;
  final List<ChannelMessage> messages;
  final List<AttachmentView> attachments;
  final List<DmOffer> dmOffers;
  final MeshInfo? mesh;
  final List<SnapshotEvent> events;

  const ChannelSnapshot({
    this.deletionSummary,
    required this.name,
    required this.topic,
    required this.meshId,
    required this.displayName,
    required this.deviceFingerprint,
    required this.messages,
    required this.attachments,
    required this.dmOffers,
    this.mesh,
    required this.events,
  });

  @override
  int get hashCode =>
      deletionSummary.hashCode ^
      name.hashCode ^
      topic.hashCode ^
      meshId.hashCode ^
      displayName.hashCode ^
      deviceFingerprint.hashCode ^
      messages.hashCode ^
      attachments.hashCode ^
      dmOffers.hashCode ^
      mesh.hashCode ^
      events.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelSnapshot &&
          runtimeType == other.runtimeType &&
          deletionSummary == other.deletionSummary &&
          name == other.name &&
          topic == other.topic &&
          meshId == other.meshId &&
          displayName == other.displayName &&
          deviceFingerprint == other.deviceFingerprint &&
          messages == other.messages &&
          attachments == other.attachments &&
          dmOffers == other.dmOffers &&
          mesh == other.mesh &&
          events == other.events;
}
