import 'dart:io';
import 'dart:convert';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mosh/src/features/conversation/conversation_details_panel.dart';
import 'package:mosh/src/features/conversation/peer_status_drawer.dart';
import 'package:mosh/src/features/sessions/sessions_screen.dart';
import 'package:mosh/src/features/shared/conversation_kind_style.dart';
import 'package:mosh/src/gateway/conversation_target.dart';
import 'package:mosh/src/rust/attachment_runtime.dart' show VoiceMeta;
import 'package:mosh/src/rust/conversation/attachments.dart';
import 'package:mosh/src/routing/app_router.dart';

import '../../support/message_builders.dart';
import '../../support/conversation_cases.dart' show testAttachment;
import '../../support/scriptable_gateway.dart';
import 'shell_harness.dart';

ScriptableGateway _gateway() {
  final now = BigInt.from(DateTime(2026, 10, 1, 14, 32).millisecondsSinceEpoch);
  final voice = AttachmentDescriptor(
    attachmentId: 'sample-voice',
    contentHash: 'voice-hash',
    fileName: 'voice.m4a',
    mime: 'audio/mp4',
    totalSize: BigInt.from(4096),
    voice: VoiceMeta(
      durationMs: 4200,
      peaksB64: base64Encode(
          Uint8List.fromList(List.generate(64, (i) => 30 + (i * 37) % 200))),
    ),
  );
  return ScriptableGateway()
    ..seedSessions([
      TestSnapshots.dm(sessionId: 'alice', peerDisplayName: 'Alice', messages: [
        TestMessages.dm(
            fromDevice: 'Alice',
            body: 'Привет! Проверим, что всё работает.',
            sentAtMs: now),
        TestMessages.dm(
            fromDevice: 'Alice',
            body: 'Как выглядит новая версия?',
            sentAtMs: now + BigInt.one),
        TestMessages.dm(
            fromDevice: 'me',
            body: 'Да, отлично. Сейчас отправлю файл.',
            attachment: testAttachment(attachmentId: 'sample-file'),
            sentAtMs: now + BigInt.one),
        TestMessages.dm(
            fromDevice: 'Alice',
            body: '',
            attachment: voice,
            sentAtMs: now + BigInt.two),
      ])
    ])
    ..seedGroups([
      TestSnapshots.group(
          groupId: 'crew',
          label: 'Design team',
          deviceFingerprint: 'self',
          inviteUri: 'mosh-group://crew',
          messages: [
            TestMessages.group(
                fromDevice: 'Alice',
                fromFingerprint: 'alice',
                body: 'Привет! Проверим, что всё работает.',
                sentAtMs: now),
            TestMessages.group(
                fromDevice: 'Alice',
                fromFingerprint: 'alice',
                body: 'Как выглядит новая версия?',
                sentAtMs: now + BigInt.one),
            TestMessages.group(
                fromDevice: 'me',
                fromFingerprint: 'self',
                body: 'Да, отлично. Сейчас отправлю файл.',
                attachment: testAttachment(attachmentId: 'group-file'),
                sentAtMs: now + BigInt.one),
            TestMessages.group(
                fromDevice: 'Bob',
                fromFingerprint: 'bob',
                body: 'Отлично, проверим права доступа для нового участника.',
                sentAtMs: now + BigInt.two),
          ])
    ])
    ..seedChannels([
      TestSnapshots.channel(
          name: 'general',
          deviceFingerprint: 'self',
          messages: [
            TestMessages.channel(
                fromDevice: 'Bob',
                fromFingerprint: 'bob',
                body: 'Новости проекта',
                sentAtMs: now),
          ])
    ]);
}

Future<void> _open(WidgetTester tester, String title) async {
  await tester.tap(find.descendant(
      of: find.byType(SessionsScreen), matching: find.text(title)));
  await tester.pumpAndSettle();
}

/// Optional exports for manual visual inspection, never generated by normal CI.
Future<void> _screenshot(WidgetTester tester, String name) async {
  const directory = String.fromEnvironment('MOSH_REDESIGN_SCREENSHOTS');
  if (directory.isEmpty) return;
  final boundary = tester
      .firstRenderObject<RenderRepaintBoundary>(find.byType(RepaintBoundary));
  await tester.runAsync(() async {
    final image = await boundary.toImage();
    final data = await image.toByteData(format: ui.ImageByteFormat.png);
    await Directory(directory).create(recursive: true);
    await File('$directory/$name.png').writeAsBytes(data!.buffer.asUint8List());
    image.dispose();
  });
}

void main() {
  testWidgets(
      'conversation types have distinct cues in rail, filter and header',
      (tester) async {
    await pumpShellApp(tester,
        gateway: _gateway(), physical: const Size(1536, 900));
    final avatars = tester.widgetList<ConversationKindAvatar>(find.descendant(
        of: find.byType(SessionsScreen),
        matching: find.byType(ConversationKindAvatar)));
    expect(avatars.map((a) => a.kind).toSet(), ConversationKind.values.toSet());
    final glyphs = <IconData>{};
    final colors = <Color>{};
    for (final kind in ConversationKind.values) {
      final avatar = find.byWidgetPredicate(
          (w) => w is ConversationKindAvatar && w.kind == kind);
      final icon = tester.widget<Icon>(
          find.descendant(of: avatar, matching: find.byIcon(kind.icon)));
      glyphs.add(icon.icon!);
      final circle = tester.widget<CircleAvatar>(
          find.descendant(of: avatar, matching: find.byType(CircleAvatar)));
      colors.add(circle.backgroundColor!);
    }
    expect(glyphs, hasLength(3));
    expect(colors, hasLength(3));
    for (final (title, kind) in [
      ('Alice', ConversationKind.dm),
      ('Design team', ConversationKind.group),
      ('#general', ConversationKind.channel),
    ]) {
      await _open(tester, title);
      final avatar = tester.widget<ConversationKindAvatar>(find.descendant(
          of: find.byType(AppBar),
          matching: find.byType(ConversationKindAvatar)));
      expect(avatar.kind, kind);
    }
    final chips = tester.widgetList<ChoiceChip>(find.byType(ChoiceChip));
    expect(chips.where((c) => c.avatar is Icon), hasLength(3));
  });
  setUp(() {
    const channel = MethodChannel('com.llfbandit.record/messages');
    TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger
        .setMockMethodCallHandler(channel, (call) async => null);
    addTearDown(() => TestDefaultBinaryMessengerBinding
        .instance.defaultBinaryMessenger
        .setMockMethodCallHandler(channel, null));
  });
  setUpAll(() async {
    const font = String.fromEnvironment('MOSH_REDESIGN_FONT');
    if (font.isEmpty) return;
    final bytes = ByteData.sublistView(await File(font).readAsBytes());
    for (final name in ['Inter Tight', 'Inter', 'Roboto', 'monospace']) {
      await (FontLoader(name)..addFont(Future.value(bytes))).load();
    }
    final icons = await rootBundle.load('fonts/MaterialIcons-Regular.otf');
    await (FontLoader('MaterialIcons')..addFont(Future.value(icons))).load();
  });
  for (final width in [320.0, 390.0, 581.0, 800.0, 1280.0, 1536.0]) {
    for (final title in ['Alice', 'Design team', '#general']) {
      testWidgets(
          '$title at ${width.toInt()}px: responsive details and usable chat',
          (tester) async {
        await pumpShellApp(tester,
            gateway: _gateway(), physical: Size(width, 900));
        await _open(tester, title);
        if (width >= 1280) {
          expect(find.byKey(const ValueKey('conversation-details-docked')),
              findsOneWidget);
          expect(find.byType(PeerStatusDrawer), findsNothing);
          if (width == 1536) {
            await _screenshot(
                tester,
                title == 'Design team'
                    ? 'desktop-group'
                    : 'desktop-${title == 'Alice' ? 'dm' : 'channel'}');
          }
          await tester.tap(find.descendant(
              of: find.byType(ConversationDetailsPanel),
              matching: find.byIcon(Icons.close)));
          await tester.pumpAndSettle();
          expect(find.byType(ConversationDetailsPanel), findsNothing);
          await tester.tap(find.byTooltip('Conversation details'));
          await tester.pumpAndSettle();
          expect(find.byKey(const ValueKey('conversation-details-docked')),
              findsOneWidget);
        } else {
          expect(find.byType(ConversationDetailsPanel), findsNothing);
          if (width == 390) {
            await _screenshot(
                tester,
                'mobile-${title == 'Alice' ? 'dm' : title == 'Design team' ? 'group' : 'channel'}');
          }
          await tester.tap(find.byTooltip('Conversation details'));
          await tester.pumpAndSettle();
          expect(find.byType(PeerStatusDrawer), findsOneWidget);
          expect(find.byType(ConversationDetailsPanel), findsOneWidget);
          await tester.sendKeyEvent(LogicalKeyboardKey.escape);
          await tester.pumpAndSettle();
          expect(find.byType(ConversationDetailsPanel), findsNothing);
        }
      });
    }
  }

  testWidgets(
      'Ctrl+K focuses the list from an active chat and returns to mobile list',
      (tester) async {
    for (final width in [1536.0, 390.0]) {
      await pumpShellApp(tester,
          gateway: _gateway(), physical: Size(width, 900));
      await _open(tester, 'Alice');
      await tester.tap(find.widgetWithText(TextField, 'Write a message…'));
      await tester.sendKeyDownEvent(LogicalKeyboardKey.controlLeft);
      await tester.sendKeyEvent(LogicalKeyboardKey.keyK);
      await tester.sendKeyUpEvent(LogicalKeyboardKey.controlLeft);
      await tester.pumpAndSettle();
      final search = tester
          .widget<TextField>(find.byKey(const ValueKey('chat-list-search')));
      expect(search.focusNode!.hasFocus, isTrue);
      if (width <= 580) {
        expect(appRouter.routeInformationProvider.value.uri.path,
            AppRoutes.sessions);
      }
    }
  });
}
