// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Device {
  final String id;
  final String name;
  final bool stable;

  const Device({
    required this.id,
    required this.name,
    required this.stable,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ stable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Device &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          stable == other.stable;
}

class Frame {
  final String sessionId;
  final String callId;
  final BigInt sequence;
  final int width;
  final int height;
  final bool local;
  final int sourceAgeMs;
  final Uint8List pixels;

  const Frame({
    required this.sessionId,
    required this.callId,
    required this.sequence,
    required this.width,
    required this.height,
    required this.local,
    required this.sourceAgeMs,
    required this.pixels,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      callId.hashCode ^
      sequence.hashCode ^
      width.hashCode ^
      height.hashCode ^
      local.hashCode ^
      sourceAgeMs.hashCode ^
      pixels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Frame &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          callId == other.callId &&
          sequence == other.sequence &&
          width == other.width &&
          height == other.height &&
          local == other.local &&
          sourceAgeMs == other.sourceAgeMs &&
          pixels == other.pixels;
}

class Snapshot {
  final String sessionId;
  final String callId;
  final bool ready;
  final bool microphone;
  final bool microphoneRequested;
  final bool microphoneAvailable;
  final bool camera;
  final bool cameraRequested;
  final bool cameraStarting;
  final bool cameraFailed;
  final bool remoteCamera;
  final bool reconnecting;
  final bool failed;
  final String? encoder;
  final String? codec;
  final int videoWidth;
  final int videoHeight;
  final double videoFps;
  final BigInt packetsDropped;
  final List<Device> inputs;
  final List<Device> outputs;
  final List<Device> cameras;
  final String? input;
  final String? output;
  final String? cameraId;

  const Snapshot({
    required this.sessionId,
    required this.callId,
    required this.ready,
    required this.microphone,
    required this.microphoneRequested,
    required this.microphoneAvailable,
    required this.camera,
    required this.cameraRequested,
    required this.cameraStarting,
    required this.cameraFailed,
    required this.remoteCamera,
    required this.reconnecting,
    required this.failed,
    this.encoder,
    this.codec,
    required this.videoWidth,
    required this.videoHeight,
    required this.videoFps,
    required this.packetsDropped,
    required this.inputs,
    required this.outputs,
    required this.cameras,
    this.input,
    this.output,
    this.cameraId,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      callId.hashCode ^
      ready.hashCode ^
      microphone.hashCode ^
      microphoneRequested.hashCode ^
      microphoneAvailable.hashCode ^
      camera.hashCode ^
      cameraRequested.hashCode ^
      cameraStarting.hashCode ^
      cameraFailed.hashCode ^
      remoteCamera.hashCode ^
      reconnecting.hashCode ^
      failed.hashCode ^
      encoder.hashCode ^
      codec.hashCode ^
      videoWidth.hashCode ^
      videoHeight.hashCode ^
      videoFps.hashCode ^
      packetsDropped.hashCode ^
      inputs.hashCode ^
      outputs.hashCode ^
      cameras.hashCode ^
      input.hashCode ^
      output.hashCode ^
      cameraId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Snapshot &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          callId == other.callId &&
          ready == other.ready &&
          microphone == other.microphone &&
          microphoneRequested == other.microphoneRequested &&
          microphoneAvailable == other.microphoneAvailable &&
          camera == other.camera &&
          cameraRequested == other.cameraRequested &&
          cameraStarting == other.cameraStarting &&
          cameraFailed == other.cameraFailed &&
          remoteCamera == other.remoteCamera &&
          reconnecting == other.reconnecting &&
          failed == other.failed &&
          encoder == other.encoder &&
          codec == other.codec &&
          videoWidth == other.videoWidth &&
          videoHeight == other.videoHeight &&
          videoFps == other.videoFps &&
          packetsDropped == other.packetsDropped &&
          inputs == other.inputs &&
          outputs == other.outputs &&
          cameras == other.cameras &&
          input == other.input &&
          output == other.output &&
          cameraId == other.cameraId;
}
