// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Lists every output device cpal can see on the default host. Devices
/// that fail to describe themselves are skipped, not fatal: a dropdown
/// with two working entries beats an error over one broken one.
List<AudioDeviceInfo> listOutputDevices() =>
    RustLib.instance.api.crateApiAudioDevicesListOutputDevices();

/// The stored input device pick, or `None` for the system default.
String? audioInputDeviceId() =>
    RustLib.instance.api.crateApiAudioDevicesAudioInputDeviceId();

/// The stored output device pick, or `None` for the system default.
String? audioOutputDeviceId() =>
    RustLib.instance.api.crateApiAudioDevicesAudioOutputDeviceId();

/// Persists BOTH picks in one write: the settings screen edits them as a
/// pair, and a partial update losing the other field would surprise the
/// user. `None` clears the pick back to the system default.
void setAudioDevices({String? inputDeviceId, String? outputDeviceId}) =>
    RustLib.instance.api.crateApiAudioDevicesSetAudioDevices(
        inputDeviceId: inputDeviceId, outputDeviceId: outputDeviceId);

/// One enumerable output device: the cpal `DeviceId` stringified (the
/// stable persisted form, `host:device`) plus the human label for the
/// dropdown.
class AudioDeviceInfo {
  /// `DeviceId::to_string()` — the value to store as the output pick.
  final String id;

  /// The device label (`Device: Display`, e.g. "Built-in Speakers").
  final String name;

  const AudioDeviceInfo({
    required this.id,
    required this.name,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioDeviceInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}
