// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../attachment_runtime.dart';
import '../channel_runtime.dart';
import '../channel_runtime/types.dart';
import '../conversation/attachments.dart';
import '../conversation/dm_offers.dart';
import '../conversation/mesh.dart';
import '../frb_generated.dart';
import '../outbound_delivery.dart';
import 'conversation_bridge.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_runtime`, `construct_runtime`, `ensure_runtime`

/// Join a public channel.
Future<ChannelSnapshot> join({required JoinChannelRequest request}) =>
    RustLib.instance.api.crateApiChannelJoin(request: request);

/// Poll a channel for its current snapshot. The Dart side polls on a cadence.
Future<ChannelSnapshot> poll({required String name}) =>
    RustLib.instance.api.crateApiChannelPoll(name: name);

/// List all joined channels and their snapshots.
Future<ChannelListSnapshot> list() =>
    RustLib.instance.api.crateApiChannelList();

/// Publish a private-DM invitation to one channel member.
Future<void> sendDmOffer(
        {required String name,
        required String targetFingerprint,
        required String inviteUri}) =>
    RustLib.instance.api.crateApiChannelSendDmOffer(
        name: name, targetFingerprint: targetFingerprint, inviteUri: inviteUri);

/// Dismiss a channel DM offer.
Future<void> dismissDmOffer({required String name, required String offerId}) =>
    RustLib.instance.api
        .crateApiChannelDismissDmOffer(name: name, offerId: offerId);
