// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../attachment_runtime.dart';
import '../frb_generated.dart';
import 'conversation_bridge.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `channel_send_attachment`, `decode_base64`, `dm_send_attachment`, `group_send_attachment`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

/// Send a text message into the conversation.
Future<void> send(
        {required BridgeConversationRef reference, required String body}) =>
    RustLib.instance.api
        .crateApiConversationSend(reference: reference, body: body);

/// Retry a failed outbound message by its message id.
Future<void> retry(
        {required BridgeConversationRef reference,
        required String messageId}) =>
    RustLib.instance.api
        .crateApiConversationRetry(reference: reference, messageId: messageId);

/// Send an attachment into the conversation. The bytes arrive base64-encoded
/// (the bridge contract every send_attachment facade keeps); a payload that
/// does not decode is `InvalidInput` before any runtime is touched. The new
/// attachment's id and hash are dropped — the next snapshot poll carries
/// them.
Future<void> sendAttachment(
        {required BridgeConversationRef reference,
        required BridgeAttachmentPayload payload}) =>
    RustLib.instance.api.crateApiConversationSendAttachment(
        reference: reference, payload: payload);

/// Begin (or retry) downloading a peer's attachment; progress is reported in
/// the next snapshot poll.
Future<void> downloadAttachment(
        {required BridgeConversationRef reference,
        required String attachmentId}) =>
    RustLib.instance.api.crateApiConversationDownloadAttachment(
        reference: reference, attachmentId: attachmentId);

/// Cancel an in-flight attachment transfer.
Future<void> cancelAttachment(
        {required BridgeConversationRef reference,
        required String attachmentId}) =>
    RustLib.instance.api.crateApiConversationCancelAttachment(
        reference: reference, attachmentId: attachmentId);

/// Leave the conversation and tear it down: `close_session` for a DM,
/// `leave` for a channel, `close` for a group — one action, three former
/// names.
Future<void> leave({required BridgeConversationRef reference}) =>
    RustLib.instance.api.crateApiConversationLeave(reference: reference);

/// One attachment send's payload: the encoded bytes plus the metadata the
/// receiver's snapshot needs. A struct rather than a parameter list because
/// the five travel together through every arm of the send.
class BridgeAttachmentPayload {
  final String fileName;
  final String mime;
  final String dataBase64;
  final String? thumbnailBase64;
  final VoiceMeta? voice;

  const BridgeAttachmentPayload({
    required this.fileName,
    required this.mime,
    required this.dataBase64,
    this.thumbnailBase64,
    this.voice,
  });

  @override
  int get hashCode =>
      fileName.hashCode ^
      mime.hashCode ^
      dataBase64.hashCode ^
      thumbnailBase64.hashCode ^
      voice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAttachmentPayload &&
          runtimeType == other.runtimeType &&
          fileName == other.fileName &&
          mime == other.mime &&
          dataBase64 == other.dataBase64 &&
          thumbnailBase64 == other.thumbnailBase64 &&
          voice == other.voice;
}

/// Which conversation kind a shared action addresses.
enum BridgeConversationKind {
  /// A private DM session (filed by session id).
  dm,

  /// A public channel (filed by name).
  channel,

  /// A private group (filed by group id).
  group,
  ;
}

/// The conversation a shared action addresses: its kind and its id — a
/// session id, a channel name, or a group id, matching the kind. A raw
/// `kind:id` string never crosses the bridge; this struct is its replacement
/// (ADR 0024).
class BridgeConversationRef {
  final BridgeConversationKind kind;
  final String id;

  const BridgeConversationRef({
    required this.kind,
    required this.id,
  });

  @override
  int get hashCode => kind.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeConversationRef &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          id == other.id;
}
