// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `unavailable`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `new`

/// One failed conversation action, as the seam reports it.
///
/// `kind` is the contract. `message` is diagnostic text; callers must not
/// branch on it because it is rendered by the runtime that produced it.
///
/// The generated Dart class gets a `toString` that returns `message`, so a
/// caller that still renders the exception as text shows the runtime's
/// sentence instead of `Instance of 'ConversationBridgeError'`.
class ConversationBridgeError implements FrbException {
  final ConversationBridgeErrorKind kind;
  final String message;

  const ConversationBridgeError({
    required this.kind,
    required this.message,
  });

  @override
  String toString() => message;

  @override
  int get hashCode => kind.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationBridgeError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message;
}

/// What the caller can do about a failed conversation action.
enum ConversationBridgeErrorKind {
  /// The request was wrong; editing it may help.
  invalidInput,

  /// The node, mesh, or signing identity is unavailable; try later.
  unavailable,

  /// The conversation is still setting up; wait for it to become ready.
  notReady,

  /// We are not in this conversation any more.
  missingConversation,

  /// The requested message does not exist.
  missingMessage,

  /// The requested attachment does not exist.
  missingAttachment,

  /// A transfer failed and can be retried from the start.
  transfer,

  /// The encrypted store or its keychain failed; retrying cannot repair it.
  persistence,

  /// The MLS history cannot be bridged; the member must rejoin.
  needsRejoin,

  /// The member's credential is no longer valid in this conversation.
  revoked,

  /// No caller-visible remedy exists for this failure.
  internal,
  ;
}
