// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../device_link/types.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `construct`, `runtime`, `with_runtime`

Future<DeviceLinkSnapshot> snapshot() =>
    RustLib.instance.api.crateApiDeviceLinkSnapshot();

Future<DeviceLinkSnapshot> createQr({required String deviceName}) =>
    RustLib.instance.api.crateApiDeviceLinkCreateQr(deviceName: deviceName);

Future<DeviceLinkSnapshot> importQr({required String uri}) =>
    RustLib.instance.api.crateApiDeviceLinkImportQr(uri: uri);

Future<DeviceLinkSnapshot> approve({required String confirmationCode}) =>
    RustLib.instance.api
        .crateApiDeviceLinkApprove(confirmationCode: confirmationCode);

Future<DeviceLinkSnapshot> cancel() =>
    RustLib.instance.api.crateApiDeviceLinkCancel();

Future<DeviceLinkSnapshot> revoke({required String deviceId}) =>
    RustLib.instance.api.crateApiDeviceLinkRevoke(deviceId: deviceId);
