// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import '../moss_runtime.dart';
import '../persistence.dart';
import '../secure_storage.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These functions are ignored because they are not marked as `pub`: `persistence_status_without_instance`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`


            /// App-level identity diagnostics. One-shot query; no lifetime params, all
/// fields are `'static` so the bridge serializes it cleanly.
Future<AppDiagnostics>  appDiagnostics() => RustLib.instance.api.crateApiDiagnosticsAppDiagnostics();

/// Per-runtime readiness diagnostics. Delegates to the mosh-core runtimes;
/// persistence reports not-available because the api facade owns no DB handle.
Future<NativeRuntimeStatus>  nativeRuntimeStatus() => RustLib.instance.api.crateApiDiagnosticsNativeRuntimeStatus();

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppDiagnostics>>
                abstract class AppDiagnostics implements RustOpaqueInterface {
                    

                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NativeRuntimeStatus>>
                abstract class NativeRuntimeStatus implements RustOpaqueInterface {
                     MossRuntimeStatus get moss;


 ResultOpenMlsRoundTripStatusString get openmlsRoundtrip;


 ResultOpenMlsSmokeStatusString get openmlsSmoke;


 PersistenceRuntimeStatus get persistence;


 SecureStorageStatus get secureStorage;


  set moss(MossRuntimeStatus moss);


  set openmlsRoundtrip(ResultOpenMlsRoundTripStatusString openmlsRoundtrip);


  set openmlsSmoke(ResultOpenMlsSmokeStatusString openmlsSmoke);


  set persistence(PersistenceRuntimeStatus persistence);


  set secureStorage(SecureStorageStatus secureStorage);



                    
                }
                
            