// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../native_call/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `hub`

Future<void> prepare(
        {required String sessionId,
        required String callId,
        required bool microphone,
        required bool camera}) =>
    RustLib.instance.api.crateApiNativeCallPrepare(
        sessionId: sessionId,
        callId: callId,
        microphone: microphone,
        camera: camera);

Future<void> setChoices(
        {required String sessionId,
        required String callId,
        required bool microphone,
        required bool microphoneAllowed,
        required bool camera,
        String? input,
        String? output,
        String? cameraId}) =>
    RustLib.instance.api.crateApiNativeCallSetChoices(
        sessionId: sessionId,
        callId: callId,
        microphone: microphone,
        microphoneAllowed: microphoneAllowed,
        camera: camera,
        input: input,
        output: output,
        cameraId: cameraId);

Future<Snapshot?> snapshot(
        {required String sessionId, required String callId}) =>
    RustLib.instance.api
        .crateApiNativeCallSnapshot(sessionId: sessionId, callId: callId);

Future<Frame?> frame(
        {required String sessionId,
        required String callId,
        required bool local,
        required BigInt after}) =>
    RustLib.instance.api.crateApiNativeCallFrame(
        sessionId: sessionId, callId: callId, local: local, after: after);
