// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../network_inventory.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Enumerate the host's network interfaces (1:1 port of the
/// `list_network_interfaces` Tauri command). Mirrors the runtime's
/// `network_inventory::list_interfaces` name so the api surface matches the
/// runtime method it delegates to.
Future<List<NetworkInterfaceInfo>> listInterfaces() =>
    RustLib.instance.api.crateApiNetworkListInterfaces();
