// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../attachment_runtime.dart';
import '../frb_generated.dart';
import '../org_runtime.dart';
import '../outbound_delivery.dart';
import '../private_dm_runtime/contracts.dart';
import '../private_group_runtime.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            

            /// Join an org from a `mosh://org` bundle URI (1:1 port of `org_join`).
Future<OrgSnapshot>  joinOrg({required JoinOrgRequest request }) => RustLib.instance.api.crateApiOrgJoinOrg(request: request);

/// Leave an org and close its bound groups (1:1 port of `org_leave`). The
/// Tauri command also closed the org's bound private groups; the future impl
/// drives both the org and group singletons from this one function.
Future<void>  leaveOrg({required String orgPubkey }) => RustLib.instance.api.crateApiOrgLeaveOrg(orgPubkey: orgPubkey);

/// List all joined orgs and their snapshots (1:1 port of `org_list`). The
/// runtime's `list` returns a `Vec<OrgSnapshot>` directly (no Result), so the
/// facade returns `Result<Vec<OrgSnapshot>, String>` to match the Tauri
/// command's `Result<Vec<OrgSnapshot>, String>` shape.
Future<List<OrgSnapshot>>  list() => RustLib.instance.api.crateApiOrgList();

/// Poll an org for its current snapshot (1:1 port of `org_poll`).
Future<OrgSnapshot>  poll({required String orgPubkey }) => RustLib.instance.api.crateApiOrgPoll(orgPubkey: orgPubkey);

/// Send a private-DM invitation to one org member (1:1 port of
/// `org_send_dm_offer`). Mints the invite via the private-DM runtime and
/// records the offer in the org runtime; the future impl drives both.
Future<InviteCreated>  sendDmOffer({required String orgPubkey , required String targetPeerId , required String displayName , required int listenPort , String? staticPeer }) => RustLib.instance.api.crateApiOrgSendDmOffer(orgPubkey: orgPubkey, targetPeerId: targetPeerId, displayName: displayName, listenPort: listenPort, staticPeer: staticPeer);

/// Accept an org-carried DM offer (1:1 port of `org_accept_dm_offer`).
/// Accepts the invite via the private-DM runtime and clears the offer in the
/// org runtime; the future impl drives both.
Future<SessionSnapshot>  acceptDmOffer({required String orgPubkey , required String offerId , required String displayName , required int listenPort , String? staticPeer }) => RustLib.instance.api.crateApiOrgAcceptDmOffer(orgPubkey: orgPubkey, offerId: offerId, displayName: displayName, listenPort: listenPort, staticPeer: staticPeer);

/// Dismiss an org DM offer (1:1 port of `org_dismiss_dm_offer`).
Future<void>  dismissDmOffer({required String orgPubkey , required String offerId }) => RustLib.instance.api.crateApiOrgDismissDmOffer(orgPubkey: orgPubkey, offerId: offerId);

/// Create an org-bound private group (1:1 port of `org_create_group`).
/// Creates the group via the private-group runtime and records the binding in
/// the org runtime; the future impl drives both.
Future<GroupCreated>  createGroup({required String orgPubkey , String? label , required List<String> memberPeerIds , required String displayName , required int listenPort , String? staticPeer }) => RustLib.instance.api.crateApiOrgCreateGroup(orgPubkey: orgPubkey, label: label, memberPeerIds: memberPeerIds, displayName: displayName, listenPort: listenPort, staticPeer: staticPeer);

/// Accept an org-carried group offer (1:1 port of `org_accept_group_offer`).
/// Joins the group via the private-group runtime and clears the offer in the
/// org runtime; the future impl drives both.
Future<GroupSnapshot>  acceptGroupOffer({required String orgPubkey , required String offerId , required String displayName , required int listenPort , String? staticPeer }) => RustLib.instance.api.crateApiOrgAcceptGroupOffer(orgPubkey: orgPubkey, offerId: offerId, displayName: displayName, listenPort: listenPort, staticPeer: staticPeer);

/// Dismiss an org group offer (1:1 port of `org_dismiss_group_offer`).
Future<void>  dismissGroupOffer({required String orgPubkey , required String offerId }) => RustLib.instance.api.crateApiOrgDismissGroupOffer(orgPubkey: orgPubkey, offerId: offerId);

/// One-click invite the roster members not yet in a group (1:1 port of
/// `org_group_invite_members`). Re-offers the group's invite URI to each
/// listed peer via the org runtime's group-offer path.
Future<void>  groupInviteMembers({required String orgPubkey , required String groupId , required List<String> memberPeerIds }) => RustLib.instance.api.crateApiOrgGroupInviteMembers(orgPubkey: orgPubkey, groupId: groupId, memberPeerIds: memberPeerIds);

            
            