// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../attachment_runtime.dart';
import '../frb_generated.dart';
import '../outbound_delivery.dart';
import '../private_dm_runtime/contracts.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These functions are ignored because they are not marked as `pub`: `build_runtime`, `construct_runtime`, `ensure_runtime`


            /// Create a private-DM invite (1:1 port of the `private_dm_create_invite`
/// Tauri command). The inviter publishes a KeyPackage and an invite URI.
Future<InviteCreated>  createInvite({required StartSessionRequest request }) => RustLib.instance.api.crateApiPrivateDmCreateInvite(request: request);

/// Accept a private-DM invite (1:1 port of `private_dm_accept_invite`). The
/// joiner parses the invite URI and processes the inviter's Welcome.
Future<SessionSnapshot>  acceptInvite({required AcceptInviteRequest request }) => RustLib.instance.api.crateApiPrivateDmAcceptInvite(request: request);

/// Send a message into a session (1:1 port of `private_dm_send_message`).
Future<SendMessageResult>  sendMessage({required String sessionId , required String body }) => RustLib.instance.api.crateApiPrivateDmSendMessage(sessionId: sessionId, body: body);

/// Poll a session for its current snapshot (1:1 port of
/// `private_dm_poll_session`). The React frontend called this every
/// AUTO_POLL_MS; no push, no StreamSink.
Future<SessionSnapshot>  pollSession({required String sessionId }) => RustLib.instance.api.crateApiPrivateDmPollSession(sessionId: sessionId);

/// List all sessions and their snapshots (1:1 port of
/// `private_dm_list_sessions`).
Future<SessionListSnapshot>  listSessions() => RustLib.instance.api.crateApiPrivateDmListSessions();

/// Close and tear down a session (1:1 port of `private_dm_close_session`).
Future<CloseSessionResult>  closeSession({required String sessionId }) => RustLib.instance.api.crateApiPrivateDmCloseSession(sessionId: sessionId);

            
            