// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../attachment_runtime.dart';
import '../conversation/attachments.dart';
import '../conversation/dm_offers.dart';
import '../conversation/mesh.dart';
import '../frb_generated.dart';
import '../outbound_delivery.dart';
import '../private_group_runtime.dart';
import 'conversation_bridge.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_runtime`, `construct_runtime`, `ensure_runtime`

/// Create a private MLS group (1:1 port of `private_group_create`).
Future<GroupCreated> createGroup({required CreateGroupRequest request}) =>
    RustLib.instance.api.crateApiPrivateGroupCreateGroup(request: request);

/// Join a private group from an invite URI (1:1 port of `private_group_join`).
Future<GroupSnapshot> joinGroup({required JoinGroupRequest request}) =>
    RustLib.instance.api.crateApiPrivateGroupJoinGroup(request: request);

/// Poll a private group for its current snapshot (1:1 port of
/// `private_group_poll`).
Future<GroupSnapshot> poll({required String groupId}) =>
    RustLib.instance.api.crateApiPrivateGroupPoll(groupId: groupId);

/// List all private groups and their snapshots (1:1 port of
/// `private_group_list`).
Future<GroupListSnapshot> list() =>
    RustLib.instance.api.crateApiPrivateGroupList();

/// Publish a private-DM invitation to one group member (1:1 port of
/// `private_group_send_dm_offer`).
Future<void> sendDmOffer(
        {required String groupId,
        required String targetFingerprint,
        required String inviteUri}) =>
    RustLib.instance.api.crateApiPrivateGroupSendDmOffer(
        groupId: groupId,
        targetFingerprint: targetFingerprint,
        inviteUri: inviteUri);

/// Dismiss a private-group DM offer (1:1 port of
/// `private_group_dismiss_dm_offer`).
Future<void> dismissDmOffer(
        {required String groupId, required String offerId}) =>
    RustLib.instance.api
        .crateApiPrivateGroupDismissDmOffer(groupId: groupId, offerId: offerId);
