// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `construct_resources`, `database_path`, `inject_once`, `resolve_data_dir`, `resolved_data_dir`, `restore_vpn_bypass`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Mobile startup may repeat the same DEK after activity recreation.
/// A different DEK would orphan the database and is refused.
Future<void> setHistoryDek({required List<int> dek}) =>
    RustLib.instance.api.crateApiSharedRuntimeSetHistoryDek(dek: dek);

/// Mobile startup may repeat the same path; a different path is refused.
Future<void> setAppDataDir({required String path}) =>
    RustLib.instance.api.crateApiSharedRuntimeSetAppDataDir(path: path);

/// Lazily construct the shared resources once, then return a clone. Each
/// runtime facade calls this at construct time and hands the clones to its
/// `from_shared_node(shared_node, attachment_store, persistence)` ctor.
Future<SharedResources> ensureSharedResources() =>
    RustLib.instance.api.crateApiSharedRuntimeEnsureSharedResources();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SharedResources>>
abstract class SharedResources implements RustOpaqueInterface {}
