// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_stream`, `fill`, `lerp`, `new`, `next_sample`, `should_resync`, `trim_to_target`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Renderer`

/// Starts the playback pipeline: an Opus decoder (48 kHz mono) + a cpal output
/// stream in the device's own format, fed from a 320 ms ring. Synchronous (audio open is blocking on
/// every cpal backend); `Err(String)` if there is no output device or
/// the stream cannot be built/started. `output_device_id` is the stored
/// audio-devices pick (cpal `DeviceId` string form); `None` or an unknown
/// id resolves to the default device (see `api::audio_devices`).
VoicePlayback voiceCallPlaybackStart({String? outputDeviceId}) =>
    RustLib.instance.api.crateApiVoiceCallPlaybackVoiceCallPlaybackStart(
        outputDeviceId: outputDeviceId);

/// Decodes one Opus packet and pushes its 960 i16 samples onto the ring. `seq`
/// is the call frame sequence (preserves gaps on the wire), unused by cpal's
/// pull model but accepted for seam parity with `VoicePlaybackHandle.pushFrame`.
/// If the ring backlog exceeds `PLAYBACK_RESYNC_S`, the oldest audio is
/// dropped down to the playout delay first. On a full ring the push trims the
/// same way and retries (no backpressure).
void voiceCallPlaybackPushFrame(
        {required VoicePlayback p,
        required BigInt seq,
        required List<int> opus}) =>
    RustLib.instance.api.crateApiVoiceCallPlaybackVoiceCallPlaybackPushFrame(
        p: p, seq: seq, opus: opus);

/// Stops the playback pipeline by dropping the `cpal::Stream` (closes the
/// audio output). The decoder and ring
/// are dropped with the `VoicePlayback` opaque when frb releases it. Inert if
/// already stopped (idempotent -- matches `VoicePlaybackHandle.stop`'s
/// "inert if already stopped" contract).
void voiceCallPlaybackStop({required VoicePlayback p}) =>
    RustLib.instance.api.crateApiVoiceCallPlaybackVoiceCallPlaybackStop(p: p);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VoicePlayback>>
abstract class VoicePlayback implements RustOpaqueInterface {}
