// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_stream`, `gain_at`, `next`, `ringtone_sample`, `write_f32`, `write_i16`, `write_u16`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SignalGenerator`

VoiceCallRingtone voiceCallRingtoneStart({String? outputDeviceId}) =>
    RustLib.instance.api.crateApiVoiceCallRingtoneVoiceCallRingtoneStart(
        outputDeviceId: outputDeviceId);

void voiceCallRingtoneStop({required VoiceCallRingtone ringtone}) =>
    RustLib.instance.api
        .crateApiVoiceCallRingtoneVoiceCallRingtoneStop(ringtone: ringtone);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VoiceCallRingtone>>
abstract class VoiceCallRingtone implements RustOpaqueInterface {}
