// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `should_resync`

/// Starts the playback pipeline: an Opus decoder (48 kHz mono) + a cpal output
/// stream fed from a 7680-sample ring. Synchronous (audio open is blocking on
/// every cpal backend); `Err(String)` if there is no default output device or
/// the stream cannot be built/started. Errors are stringified via `Debug`,
/// matching `voice_call_opus_encode`'s `Result<T, String>` style.
VoicePlayback voiceCallPlaybackStart() =>
    RustLib.instance.api.crateApiVoiceCallPlaybackVoiceCallPlaybackStart();

/// Decodes one Opus packet and pushes its 960 i16 samples onto the ring. `seq`
/// is the call frame sequence (preserves gaps on the wire, mirroring React's
/// `(seq & SEQ_VALUE_MASK) * 20000us` timestamp), unused by cpal's pull model
/// but accepted for seam parity with `VoicePlaybackHandle.pushFrame`. If the
/// ring backlog exceeds `PLAYBACK_RESYNC_S`, the backlog is dropped first
/// (React's `start = currentTime` resync). On a full ring the push clears the
/// backlog and retries, matching React's no-backpressure `source.start(0)`
/// "play from now" behavior.
void voiceCallPlaybackPushFrame(
        {required VoicePlayback p,
        required BigInt seq,
        required List<int> opus}) =>
    RustLib.instance.api.crateApiVoiceCallPlaybackVoiceCallPlaybackPushFrame(
        p: p, seq: seq, opus: opus);

/// Stops the playback pipeline by dropping the `cpal::Stream` (closes the
/// audio output, mirroring React's `context.close()`). The decoder and ring
/// are dropped with the `VoicePlayback` opaque when frb releases it. Inert if
/// already stopped (idempotent -- matches `VoicePlaybackHandle.stop`'s
/// "inert if already stopped" contract).
void voiceCallPlaybackStop({required VoicePlayback p}) =>
    RustLib.instance.api.crateApiVoiceCallPlaybackVoiceCallPlaybackStop(p: p);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VoicePlayback>>
abstract class VoicePlayback implements RustOpaqueInterface {}
