// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Constructs a 48 kHz mono VoIP Opus encoder at 24 kbps, mirroring the React
/// WebCodecs encoder config. Synchronous (no I/O); `Err(String)` on libopus
/// init or bitrate-set failure. Errors are stringified via `Debug` to keep the
/// bridge surface a plain `Result<T, String>` (matches `voice_call_*` style).
VoiceCallOpusEncoder voiceCallOpusEncoderNew() =>
    RustLib.instance.api.crateApiVoiceCallOpusEncodeVoiceCallOpusEncoderNew();

/// Encodes one 20 ms PCM16 frame to an Opus packet. `pcm16` is 1920 bytes (960
/// little-endian i16 samples, host-native from `record`'s `pcm16bits` stream);
/// any other length is rejected so a framing slip surfaces as a hard error
/// rather than a silently mis-encoded frame. Returns the Opus packet bytes
/// (1-3 bytes for a DTX comfort-noise frame, longer for real speech). The
/// encoder is locked for the duration of the encode (single-threaded use).
Uint8List voiceCallOpusEncode(
        {required VoiceCallOpusEncoder encoder, required List<int> pcm16}) =>
    RustLib.instance.api.crateApiVoiceCallOpusEncodeVoiceCallOpusEncode(
        encoder: encoder, pcm16: pcm16);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VoiceCallOpusEncoder>>
abstract class VoiceCallOpusEncoder implements RustOpaqueInterface {}
