// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../vpn_consent.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`


            /// Detect whether a VPN appears to own the default route (1:1 port of the
/// `detect_vpn` Tauri command).
Future<VpnDetection>  detectVpn() => RustLib.instance.api.crateApiVpnDetectVpn();

/// Report the interface the live Moss node is currently bound to (1:1 port
/// of `get_bind_interface`). `None` before any node has started; matches the
/// Tauri command's `Option<String>` return shape directly (no Result wrap —
/// the Tauri command returned `Option<String>`, not `Result`).
Future<String?>  getBindInterface() => RustLib.instance.api.crateApiVpnGetBindInterface();

/// Read the stored VPN-bypass consent (1:1 port of
/// `get_vpn_bypass_consent`). `None` means no prior answer; the bridge asks
/// again next launch. Matches the Tauri command's
/// `Option<VpnBypassConsent>` return shape directly (no Result wrap).
Future<VpnBypassConsent?>  getVpnBypassConsent() => RustLib.instance.api.crateApiVpnGetVpnBypassConsent();

/// Record the VPN-bypass consent (1:1 port of `set_vpn_bypass_consent`).
/// `Some(name)` is a yes (remembered); `None` is a refusal (deliberately not
/// stored, so the question returns next launch). The future impl validates
/// the interface against `network_inventory::list_interfaces` before
/// saving, exactly as the Tauri command did.
Future<void>  setVpnBypassConsent({String? interface_ }) => RustLib.instance.api.crateApiVpnSetVpnBypassConsent(interface_: interface_);

            /// VPN-detection result. Verbatim port of the struct the former Tauri shell
/// defined inline for the `detect_vpn` command, owned here so the bridge
/// serializes it without touching a Tauri-typed type.
class VpnDetection  {
                final bool vpnLikely;
final List<String> suspectInterfaces;
/// True when the IPv4 default route currently points through a
/// virtual / tunnel interface — the strongest signal that an active
/// VPN owns the user's outbound traffic right now.
final bool vpnOwnsDefaultRoute;

                const VpnDetection({required this.vpnLikely ,required this.suspectInterfaces ,required this.vpnOwnsDefaultRoute ,});

                
                

                
        @override
        int get hashCode => vpnLikely.hashCode^suspectInterfaces.hashCode^vpnOwnsDefaultRoute.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is VpnDetection &&
                runtimeType == other.runtimeType
                && vpnLikely == other.vpnLikely&& suspectInterfaces == other.suspectInterfaces&& vpnOwnsDefaultRoute == other.vpnOwnsDefaultRoute;
        
            }
            