// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ChatNameEntry {
  final String conversationKey;
  final String name;

  const ChatNameEntry({
    required this.conversationKey,
    required this.name,
  });

  @override
  int get hashCode => conversationKey.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatNameEntry &&
          runtimeType == other.runtimeType &&
          conversationKey == other.conversationKey &&
          name == other.name;
}

class ChatNameSnapshot {
  final List<ChatNameEntry> entries;
  final bool pending;

  const ChatNameSnapshot({
    required this.entries,
    required this.pending,
  });

  @override
  int get hashCode => entries.hashCode ^ pending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatNameSnapshot &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          pending == other.pending;
}
